import { describe, it, expect } from 'vitest';
import { exportDrizzle } from '../drizzle-export';
import { DatabaseType } from '@/lib/domain/database-type';
import type { Diagram } from '@/lib/domain/diagram';
import type { DBTable } from '@/lib/domain/db-table';
import type { DBField } from '@/lib/domain/db-field';
import type { DBRelationship } from '@/lib/domain/db-relationship';
import { DBCustomTypeKind } from '@/lib/domain/db-custom-type';

// --- Helpers ---

function makeField(overrides: Partial<DBField> & { name: string }): DBField {
    const { name, ...rest } = overrides;
    return {
        id: rest.id ?? name,
        type: { id: 'text', name: 'text' },
        primaryKey: false,
        unique: false,
        nullable: true,
        createdAt: Date.now(),
        ...rest,
        name,
    };
}

function makeTable(
    overrides: Partial<DBTable> & { name: string; fields: DBField[] }
): DBTable {
    const { name, fields, ...rest } = overrides;
    return {
        id: rest.id ?? name,
        schema: '',
        x: 0,
        y: 0,
        color: '#1a1a2e',
        isView: false,
        createdAt: Date.now(),
        indexes: [],
        order: 0,
        ...rest,
        name,
        fields,
    };
}

function makeDiagram(
    overrides: Partial<Diagram> & { databaseType: DatabaseType }
): Diagram {
    return {
        id: 'test-diagram',
        name: 'Test',
        createdAt: new Date(),
        updatedAt: new Date(),
        tables: [],
        relationships: [],
        customTypes: [],
        ...overrides,
    };
}

function makeRelationship(
    overrides: Partial<DBRelationship> & {
        sourceTableId: string;
        targetTableId: string;
        sourceFieldId: string;
        targetFieldId: string;
    }
): DBRelationship {
    return {
        id:
            overrides.id ??
            `${overrides.sourceTableId}_${overrides.sourceFieldId}`,
        name: overrides.name ?? '',
        sourceCardinality: overrides.sourceCardinality ?? 'many',
        targetCardinality: overrides.targetCardinality ?? 'one',
        createdAt: Date.now(),
        ...overrides,
    };
}

// --- Tests ---

describe('exportDrizzle', () => {
    describe('header and imports', () => {
        it('should include BoringDB header comment', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                }),
            });
            expect(result).toContain('// Schema generated by BoringDB');
        });

        it('should import from pg-core for PostgreSQL', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain("from 'drizzle-orm/pg-core'");
            expect(result).toContain('pgTable');
        });

        it('should import from mysql-core for MySQL', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.MYSQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'int', name: 'int' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain("from 'drizzle-orm/mysql-core'");
            expect(result).toContain('mysqlTable');
        });

        it('should import from sqlite-core for SQLite', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.SQLITE,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'integer', name: 'integer' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain("from 'drizzle-orm/sqlite-core'");
            expect(result).toContain('sqliteTable');
        });

        it('should import relations from drizzle-orm when relationships exist', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'posts',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                                makeField({
                                    name: 'user_id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            sourceTableId: 'posts',
                            targetTableId: 'users',
                            sourceFieldId: 'user_id',
                            targetFieldId: 'id',
                        }),
                    ],
                }),
            });
            expect(result).toContain("from 'drizzle-orm'");
            expect(result).toContain('relations');
        });

        it('should import sql when SQL expressions in defaults', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'items',
                            fields: [
                                makeField({
                                    name: 'data',
                                    type: { id: 'jsonb', name: 'jsonb' },
                                    default: "jsonb_build_object('key', 'val')",
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('sql');
            expect(result).toContain("from 'drizzle-orm'");
        });
    });

    describe('PostgreSQL type mapping', () => {
        function pgExport(fields: DBField[]): string {
            return exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [makeTable({ name: 'test', fields })],
                }),
            });
        }

        it('should map integer types correctly', () => {
            const result = pgExport([
                makeField({
                    name: 'a',
                    type: { id: 'integer', name: 'integer' },
                }),
                makeField({
                    name: 'b',
                    type: { id: 'bigint', name: 'bigint' },
                }),
                makeField({
                    name: 'c',
                    type: { id: 'smallint', name: 'smallint' },
                }),
            ]);
            expect(result).toContain("integer('a')");
            expect(result).toContain("bigint('b', { mode: 'bigint' })");
            expect(result).toContain("smallint('c')");
        });

        it('should map serial types correctly', () => {
            const result = pgExport([
                makeField({
                    name: 'a',
                    type: { id: 'serial', name: 'serial' },
                }),
                makeField({
                    name: 'b',
                    type: { id: 'bigserial', name: 'bigserial' },
                }),
            ]);
            expect(result).toContain("serial('a')");
            expect(result).toContain("bigserial('b')");
        });

        it('should map varchar with optional length', () => {
            const result = pgExport([
                makeField({
                    name: 'a',
                    type: { id: 'varchar', name: 'varchar' },
                    characterMaximumLength: '255',
                }),
                makeField({
                    name: 'b',
                    type: { id: 'varchar', name: 'varchar' },
                }),
            ]);
            expect(result).toContain("varchar('a', { length: 255 })");
            expect(result).toContain("varchar('b')");
        });

        it('should map timestamp with timezone', () => {
            const result = pgExport([
                makeField({
                    name: 'a',
                    type: { id: 'timestamp', name: 'timestamp' },
                }),
                makeField({
                    name: 'b',
                    type: { id: 'timestamptz', name: 'timestamptz' },
                }),
            ]);
            expect(result).toContain("timestamp('a')");
            expect(result).toContain("timestamp('b', { withTimezone: true })");
        });

        it('should map numeric with precision and scale', () => {
            const result = pgExport([
                makeField({
                    name: 'price',
                    type: { id: 'numeric', name: 'numeric' },
                    precision: 10,
                    scale: 2,
                }),
            ]);
            expect(result).toContain(
                "numeric('price', { precision: 10, scale: 2 })"
            );
        });

        it('should map numeric with scale of 0 (not falsy)', () => {
            const result = pgExport([
                makeField({
                    name: 'count',
                    type: { id: 'numeric', name: 'numeric' },
                    precision: 10,
                    scale: 0,
                }),
            ]);
            expect(result).toContain(
                "numeric('count', { precision: 10, scale: 0 })"
            );
        });

        it('should map json and jsonb types', () => {
            const result = pgExport([
                makeField({ name: 'a', type: { id: 'json', name: 'json' } }),
                makeField({ name: 'b', type: { id: 'jsonb', name: 'jsonb' } }),
            ]);
            expect(result).toContain("json('a')");
            expect(result).toContain("jsonb('b')");
        });

        it('should map uuid type', () => {
            const result = pgExport([
                makeField({ name: 'id', type: { id: 'uuid', name: 'uuid' } }),
            ]);
            expect(result).toContain("uuid('id')");
        });

        it('should map network types', () => {
            const result = pgExport([
                makeField({ name: 'ip', type: { id: 'inet', name: 'inet' } }),
                makeField({ name: 'net', type: { id: 'cidr', name: 'cidr' } }),
                makeField({
                    name: 'mac',
                    type: { id: 'macaddr', name: 'macaddr' },
                }),
            ]);
            expect(result).toContain("inet('ip')");
            expect(result).toContain("cidr('net')");
            expect(result).toContain("macaddr('mac')");
        });
    });

    describe('MySQL type mapping', () => {
        function mysqlExport(fields: DBField[]): string {
            return exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.MYSQL,
                    tables: [makeTable({ name: 'test', fields })],
                }),
            });
        }

        it('should map bigint with mode', () => {
            const result = mysqlExport([
                makeField({
                    name: 'big',
                    type: { id: 'bigint', name: 'bigint' },
                }),
            ]);
            expect(result).toContain("bigint('big', { mode: 'bigint' })");
        });

        it('should map varchar with required length', () => {
            const result = mysqlExport([
                makeField({
                    name: 'name',
                    type: { id: 'varchar', name: 'varchar' },
                }),
            ]);
            // MySQL varchar defaults to length 255
            expect(result).toContain("varchar('name', { length: 255 })");
        });

        it('should map text variants', () => {
            const result = mysqlExport([
                makeField({
                    name: 'a',
                    type: { id: 'tinytext', name: 'tinytext' },
                }),
                makeField({
                    name: 'b',
                    type: { id: 'mediumtext', name: 'mediumtext' },
                }),
                makeField({
                    name: 'c',
                    type: { id: 'longtext', name: 'longtext' },
                }),
            ]);
            expect(result).toContain("tinytext('a')");
            expect(result).toContain("mediumtext('b')");
            expect(result).toContain("longtext('c')");
        });

        it('should map datetime and date', () => {
            const result = mysqlExport([
                makeField({
                    name: 'a',
                    type: { id: 'datetime', name: 'datetime' },
                }),
                makeField({ name: 'b', type: { id: 'date', name: 'date' } }),
            ]);
            expect(result).toContain("datetime('a')");
            expect(result).toContain("date('b')");
        });

        it('should map uuid to char(36)', () => {
            const result = mysqlExport([
                makeField({ name: 'id', type: { id: 'uuid', name: 'uuid' } }),
            ]);
            expect(result).toContain("char('id', { length: 36 })");
        });
    });

    describe('SQLite type mapping', () => {
        function sqliteExport(fields: DBField[]): string {
            return exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.SQLITE,
                    tables: [makeTable({ name: 'test', fields })],
                }),
            });
        }

        it('should map all integer variants to integer()', () => {
            const result = sqliteExport([
                makeField({
                    name: 'a',
                    type: { id: 'integer', name: 'integer' },
                }),
                makeField({
                    name: 'b',
                    type: { id: 'bigint', name: 'bigint' },
                }),
                makeField({
                    name: 'c',
                    type: { id: 'smallint', name: 'smallint' },
                }),
            ]);
            expect(result).toContain("integer('a')");
            expect(result).toContain("integer('b')");
            expect(result).toContain("integer('c')");
        });

        it('should map boolean to integer with mode boolean', () => {
            const result = sqliteExport([
                makeField({
                    name: 'active',
                    type: { id: 'boolean', name: 'boolean' },
                }),
            ]);
            expect(result).toContain("integer('active', { mode: 'boolean' })");
        });

        it('should map timestamp to integer with mode timestamp', () => {
            const result = sqliteExport([
                makeField({
                    name: 'at',
                    type: { id: 'timestamp', name: 'timestamp' },
                }),
            ]);
            expect(result).toContain("integer('at', { mode: 'timestamp' })");
        });

        it('should map json to text with mode json', () => {
            const result = sqliteExport([
                makeField({ name: 'data', type: { id: 'json', name: 'json' } }),
            ]);
            expect(result).toContain("text('data', { mode: 'json' })");
        });

        it('should map blob to blob()', () => {
            const result = sqliteExport([
                makeField({ name: 'bin', type: { id: 'blob', name: 'blob' } }),
            ]);
            expect(result).toContain("blob('bin')");
        });

        it('should map numeric to numeric()', () => {
            const result = sqliteExport([
                makeField({
                    name: 'val',
                    type: { id: 'numeric', name: 'numeric' },
                }),
            ]);
            expect(result).toContain("numeric('val')");
        });
    });

    describe('modifiers', () => {
        it('should add .primaryKey()', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.primaryKey()');
        });

        it('should add .notNull() for non-nullable non-PK fields', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'email',
                                    type: { id: 'varchar', name: 'varchar' },
                                    nullable: false,
                                    characterMaximumLength: '255',
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.notNull()');
        });

        it('should NOT add .notNull() for primary keys', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'integer', name: 'integer' },
                                    primaryKey: true,
                                    nullable: false,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            // Should have .primaryKey() but NOT .notNull()
            expect(result).toContain('.primaryKey()');
            expect(result).not.toContain('.notNull()');
        });

        it('should NOT add .notNull() for PG serial types', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    nullable: false,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).not.toContain('.notNull()');
        });

        it('should add .unique() for non-PK unique fields', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'email',
                                    type: { id: 'varchar', name: 'varchar' },
                                    unique: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.unique()');
        });

        it('should add .default() for various default types', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'items',
                            fields: [
                                makeField({
                                    name: 'created',
                                    type: {
                                        id: 'timestamptz',
                                        name: 'timestamptz',
                                    },
                                    default: 'now()',
                                }),
                                makeField({
                                    name: 'active',
                                    type: { id: 'boolean', name: 'boolean' },
                                    default: 'true',
                                }),
                                makeField({
                                    name: 'count',
                                    type: { id: 'integer', name: 'integer' },
                                    default: '0',
                                }),
                                makeField({
                                    name: 'status',
                                    type: { id: 'varchar', name: 'varchar' },
                                    default: "'pending'",
                                }),
                                makeField({
                                    name: 'uid',
                                    type: { id: 'uuid', name: 'uuid' },
                                    default: 'gen_random_uuid()',
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.defaultNow()');
            expect(result).toContain('.default(true)');
            expect(result).toContain('.default(0)');
            expect(result).toContain(".default('pending')");
            expect(result).toContain('.defaultRandom()');
        });

        it('should add .references() for FK fields', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'posts',
                            fields: [
                                makeField({
                                    name: 'user_id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            sourceTableId: 'posts',
                            targetTableId: 'users',
                            sourceFieldId: 'user_id',
                            targetFieldId: 'id',
                        }),
                    ],
                }),
            });
            expect(result).toContain('.references(() => users.id)');
        });

        it('should add .array() for PG array fields', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'items',
                            fields: [
                                makeField({
                                    name: 'tags',
                                    type: { id: 'text', name: 'text' },
                                    isArray: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.array()');
        });

        it('should add autoIncrement for SQLite PK with increment', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.SQLITE,
                    tables: [
                        makeTable({
                            name: 'items',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'integer', name: 'integer' },
                                    primaryKey: true,
                                    increment: true,
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('.primaryKey({ autoIncrement: true })');
        });
    });

    describe('identifiers', () => {
        it('should convert snake_case to camelCase', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'user_profiles',
                            fields: [
                                makeField({
                                    name: 'first_name',
                                    type: { id: 'text', name: 'text' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('export const userProfiles');
            expect(result).toContain('firstName:');
        });

        it('should handle hyphens in identifiers', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'my-table',
                            fields: [
                                makeField({
                                    name: 'first-name',
                                    type: { id: 'text', name: 'text' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('export const myTable');
            expect(result).toContain('firstName:');
        });

        it('should handle digit-prefixed names', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: '2fa_codes',
                            fields: [
                                makeField({
                                    name: 'code',
                                    type: { id: 'text', name: 'text' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            // Should prefix with underscore
            expect(result).toContain('export const _2faCodes');
        });

        it('should handle JS reserved words', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'class',
                            fields: [
                                makeField({
                                    name: 'default',
                                    type: { id: 'text', name: 'text' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain('export const classTable');
            expect(result).toContain('defaultTable:');
        });

        it('should preserve original table name in constructor string', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'user_profiles',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            // Variable is camelCase, but SQL table name is preserved
            expect(result).toContain("pgTable('user_profiles'");
        });
    });

    describe('indexes', () => {
        it('should generate index() for non-unique indexes', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'email',
                                    type: { id: 'varchar', name: 'varchar' },
                                }),
                            ],
                            indexes: [
                                {
                                    id: 'idx1',
                                    name: 'idx_users_email',
                                    fieldIds: ['email'],
                                    unique: false,
                                    isPrimaryKey: false,
                                    createdAt: Date.now(),
                                },
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain("index('idx_users_email')");
        });

        it('should generate uniqueIndex() for unique indexes', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'email',
                                    type: { id: 'varchar', name: 'varchar' },
                                }),
                            ],
                            indexes: [
                                {
                                    id: 'idx1',
                                    name: 'uniq_email',
                                    fieldIds: ['email'],
                                    unique: true,
                                    isPrimaryKey: false,
                                    createdAt: Date.now(),
                                },
                            ],
                        }),
                    ],
                }),
            });
            expect(result).toContain("uniqueIndex('uniq_email')");
        });

        it('should skip primary key indexes', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                            indexes: [
                                {
                                    id: 'pk',
                                    name: 'users_pkey',
                                    fieldIds: ['id'],
                                    unique: true,
                                    isPrimaryKey: true,
                                    createdAt: Date.now(),
                                },
                            ],
                        }),
                    ],
                }),
            });
            expect(result).not.toContain("uniqueIndex('users_pkey')");
        });
    });

    describe('relations', () => {
        it('should generate one() on FK holder side', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'posts',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                                makeField({
                                    name: 'user_id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            sourceTableId: 'posts',
                            targetTableId: 'users',
                            sourceFieldId: 'user_id',
                            targetFieldId: 'id',
                        }),
                    ],
                }),
            });
            expect(result).toContain('postsRelations');
            expect(result).toContain('users: one(users');
            expect(result).toContain('posts.userId');
            expect(result).toContain('users.id');
        });

        it('should generate many() on referenced side for 1:many', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'posts',
                            fields: [
                                makeField({
                                    name: 'user_id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            sourceTableId: 'posts',
                            targetTableId: 'users',
                            sourceFieldId: 'user_id',
                            targetFieldId: 'id',
                            sourceCardinality: 'many',
                            targetCardinality: 'one',
                        }),
                    ],
                }),
            });
            expect(result).toContain('usersRelations');
            expect(result).toContain('posts: many(posts)');
        });

        it('should generate one() on referenced side for 1:1', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'profiles',
                            fields: [
                                makeField({
                                    name: 'user_id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            sourceTableId: 'profiles',
                            targetTableId: 'users',
                            sourceFieldId: 'user_id',
                            targetFieldId: 'id',
                            sourceCardinality: 'one',
                            targetCardinality: 'one',
                        }),
                    ],
                }),
            });
            expect(result).toContain('usersRelations');
            expect(result).toContain('profiles: one(profiles)');
        });

        it('should disambiguate multiple FKs to same table', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                    primaryKey: true,
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'orders',
                            fields: [
                                makeField({
                                    name: 'created_by',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                                makeField({
                                    name: 'updated_by',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                        }),
                    ],
                    relationships: [
                        makeRelationship({
                            id: 'rel1',
                            sourceTableId: 'orders',
                            targetTableId: 'users',
                            sourceFieldId: 'created_by',
                            targetFieldId: 'id',
                        }),
                        makeRelationship({
                            id: 'rel2',
                            sourceTableId: 'orders',
                            targetTableId: 'users',
                            sourceFieldId: 'updated_by',
                            targetFieldId: 'id',
                        }),
                    ],
                }),
            });
            // First FK uses base name, second gets suffixed
            expect(result).toContain('users: one(users');
            expect(result).toContain('users_updatedBy: one(users');
        });
    });

    describe('enum support', () => {
        it('should generate pgEnum declarations for PostgreSQL', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'orders',
                            fields: [
                                makeField({
                                    name: 'status',
                                    type: { id: 'enum', name: 'order_status' },
                                }),
                            ],
                        }),
                    ],
                    customTypes: [
                        {
                            id: 'ct1',
                            name: 'order_status',
                            kind: DBCustomTypeKind.enum,
                            values: ['pending', 'shipped', 'delivered'],
                        },
                    ],
                }),
            });
            expect(result).toContain('pgEnum');
            expect(result).toContain(
                "export const orderStatusEnum = pgEnum('order_status', ['pending', 'shipped', 'delivered'])"
            );
            expect(result).toContain("orderStatusEnum('status')");
        });

        it('should generate mysqlEnum inline for MySQL', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.MYSQL,
                    tables: [
                        makeTable({
                            name: 'orders',
                            fields: [
                                makeField({
                                    name: 'status',
                                    type: { id: 'enum', name: 'order_status' },
                                }),
                            ],
                        }),
                    ],
                    customTypes: [
                        {
                            id: 'ct1',
                            name: 'order_status',
                            kind: DBCustomTypeKind.enum,
                            values: ['pending', 'shipped', 'delivered'],
                        },
                    ],
                }),
            });
            expect(result).toContain('mysqlEnum');
            expect(result).toContain(
                "mysqlEnum('status', ['pending', 'shipped', 'delivered'])"
            );
        });

        it('should fall back to text for SQLite enums', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.SQLITE,
                    tables: [
                        makeTable({
                            name: 'orders',
                            fields: [
                                makeField({
                                    name: 'status',
                                    type: { id: 'enum', name: 'order_status' },
                                }),
                            ],
                        }),
                    ],
                    customTypes: [
                        {
                            id: 'ct1',
                            name: 'order_status',
                            kind: DBCustomTypeKind.enum,
                            values: ['pending', 'shipped', 'delivered'],
                        },
                    ],
                }),
            });
            expect(result).toContain("text('status')");
            expect(result).not.toContain('Enum');
        });

        it('should handle enum with no matching custom type gracefully', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'items',
                            fields: [
                                makeField({
                                    name: 'kind',
                                    type: { id: 'enum', name: 'unknown_enum' },
                                }),
                            ],
                        }),
                    ],
                }),
            });
            // Falls through to default (text)
            expect(result).toContain("text('kind')");
        });
    });

    describe('views filtering', () => {
        it('should skip views', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                    tables: [
                        makeTable({
                            name: 'users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'serial', name: 'serial' },
                                }),
                            ],
                        }),
                        makeTable({
                            name: 'active_users',
                            fields: [
                                makeField({
                                    name: 'id',
                                    type: { id: 'integer', name: 'integer' },
                                }),
                            ],
                            isView: true,
                        }),
                    ],
                }),
            });
            expect(result).toContain('export const users');
            expect(result).not.toContain('activeUsers');
        });
    });

    describe('empty diagram', () => {
        it('should produce valid output for empty diagram', () => {
            const result = exportDrizzle({
                diagram: makeDiagram({
                    databaseType: DatabaseType.POSTGRESQL,
                }),
            });
            expect(result).toContain('// Schema generated by BoringDB');
            expect(result).toContain("from 'drizzle-orm/pg-core'");
        });
    });
});
