import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/ai-gateway.png';
import imageDark from '@/assets/templates/ai-gateway-dark.png';

const now = Date.now();

export const aiGatewayDb: Template = {
    slug: 'ai-gateway',
    name: 'AI Gateway',
    shortDescription:
        'LLM API gateway with routing, caching, and cost tracking',
    description:
        'Route, rate-limit, cache, and monitor LLM API calls across providers',
    image,
    imageDark,
    tags: ['Postgres', 'AI', 'Infrastructure'],
    featured: true,
    diagram: {
        id: 'ai_gateway_db',
        name: 'ai-gateway',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: 'd86l4o08l6u4ahnz359c9jt57',
                name: 'providers',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'rc0cb77khl4nisoa2wb4dn2g6',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'o2pkis67b235xv0zksp9u4erv',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'u8fdq61i2ducrqmwi4jasdpse',
                        name: 'base_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '50wyyv1bbn6e4u8m846h47mbv',
                        name: 'auth_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'bearer'",
                        createdAt: now,
                    },
                    {
                        id: '6pigavkngjklykbttyx9tyyzo',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'r7tgys3eqmf3wh92lg0vihnuw',
                        name: 'default_timeout_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '30000',
                        createdAt: now,
                    },
                    {
                        id: 'g8k5cnn3yhpgpoez30bzvci7l',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'e47hen9sfk2vbv24rfm12llaa',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'dvbvai77in3chtvzevjvg2dy1',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'i1okf3gf9jyzoykl133bakg1q',
                        name: 'providers_pkey',
                        unique: true,
                        fieldIds: ['rc0cb77khl4nisoa2wb4dn2g6'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'lhokeefo2ecg6oxys06d5rxqb',
                name: 'models',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: '6ppqm28gbgftnwvfylnu1ztok',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '39iynubmd70osz71nlfg2g4us',
                        name: 'provider_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3ljjci6e9u5w8yg6l7pazjfan',
                        name: 'model_id',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'bxhkw46a563unasewggt5q4tw',
                        name: 'display_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '4iubqi5ata5s9wg4bm15m9yxv',
                        name: 'input_cost_per_million',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        createdAt: now,
                    },
                    {
                        id: 'ke5oqy9ssoom9j63og1q687i8',
                        name: 'output_cost_per_million',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        createdAt: now,
                    },
                    {
                        id: 'vwtcc40bjw4qiabx0lu1ja254',
                        name: 'max_context_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rreqep33mxbyanri8m5wkowrp',
                        name: 'supports_streaming',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'jkvjzsqn494v0chbabus4m6x3',
                        name: 'supports_tools',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'tw9mn8usw34z6wb9sp2qfitks',
                        name: 'supports_vision',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: '0ltyxpb5jl3ewn9bietsmwnbb',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: '5vdsq6oxern05520mjcho91ho',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'pf2bc4mlgyuelp5n6syald7l2',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'ht94mdjq2dxhys4m8pagwreq2',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'lf0c7u6s1hk3fedcp9mbjm26x',
                        name: 'models_pkey',
                        unique: true,
                        fieldIds: ['6ppqm28gbgftnwvfylnu1ztok'],
                        createdAt: now,
                    },
                    {
                        id: 'guq3l757pnodag06qrz1hwhk1',
                        name: 'idx_models_provider',
                        unique: false,
                        fieldIds: ['39iynubmd70osz71nlfg2g4us'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'lhonywx5ymd5553yxxse3xgx2',
                name: 'api_keys',
                schema: 'public',
                x: 900,
                y: 100,
                fields: [
                    {
                        id: 'b89or8idtjp66bipd1f6ah9rp',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'd8rqhc4htlmwhtd25klyyoizi',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'npn7w3tijw4rtgawgiamn0rbk',
                        name: 'key_hash',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: '2wffrn5hxh6eik30ydurwoyhf',
                        name: 'key_prefix',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '8',
                        createdAt: now,
                    },
                    {
                        id: 'rkqr3ii3r1ok9wttndgs6gr0b',
                        name: 'provider_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '04vzgdmotssu8cwr186neosc3',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: '987pabs3cy0u26janyrb4zb2b',
                        name: 'rate_limit_rpm',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '97q43ykfinzz73r8hcbydabdm',
                        name: 'rate_limit_tpm',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'reqq9f5ozcw2nwv8x16c7xrnt',
                        name: 'monthly_budget_cents',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'y9xjomr6j5ipijsslb5d1arlr',
                        name: 'expires_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0tahvnftyouxtf9jxi1mn31hs',
                        name: 'last_used_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wvaqxwtq1ymtna3eya9dyzg94',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'x9bnpt0uxuww2aiou7ssb5tzn',
                        name: 'api_keys_pkey',
                        unique: true,
                        fieldIds: ['b89or8idtjp66bipd1f6ah9rp'],
                        createdAt: now,
                    },
                    {
                        id: 'd2v5dcnwk04e6h6aega4xagse',
                        name: 'idx_api_keys_prefix',
                        unique: false,
                        fieldIds: ['2wffrn5hxh6eik30ydurwoyhf'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'tc8u3dcs5ycy6q5wovymdyr0e',
                name: 'routing_rules',
                schema: 'public',
                x: 1300,
                y: 100,
                fields: [
                    {
                        id: '63za17nil1bd1pqnk2ywsb9kw',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '1gpmnyihlhutsxr4jkcpwimip',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'dumfa9zgku0v11sxpomapwbht',
                        name: 'priority',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '5gcl3buoltpbs9s8sj24fbyqv',
                        name: 'match_model_pattern',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'odkrohrg74doojfz510x5h3jq',
                        name: 'match_metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cw393oxwnwyb9aax3d4k8b2f3',
                        name: 'target_provider_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vg3v2hvv6nnokncc2xut65zmb',
                        name: 'target_model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '6pk6yusrdwxsuv7pxm4go3rso',
                        name: 'weight',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '100',
                        createdAt: now,
                    },
                    {
                        id: 'yjjfsstnhc7alrtjohwc66w2n',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: '9wfze3bmab11nwfpvpuk7xze0',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: '9hgb7t2uul0qpiwmyx0w96lzu',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2qfnbwx2uqbxo2qwwc7eo918i',
                        name: 'routing_rules_pkey',
                        unique: true,
                        fieldIds: ['63za17nil1bd1pqnk2ywsb9kw'],
                        createdAt: now,
                    },
                    {
                        id: 'w4w9p6pqkxld5gtxx21zxs0m1',
                        name: 'idx_routing_rules_priority',
                        unique: false,
                        fieldIds: ['dumfa9zgku0v11sxpomapwbht'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'md438ung1shwj1i4ck38kf346',
                name: 'fallback_chains',
                schema: 'public',
                x: 100,
                y: 600,
                fields: [
                    {
                        id: '1l0tyeqlfrobz65otktl8k3tn',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'el7pn672pqfyov84suclkhrb3',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'u26myr33mk5yrugczt9bblao6',
                        name: 'primary_model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'quloubk5u7y6txu8xx2sutj7e',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'l3odrmexv6afwl7yb03djwuwx',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '9vnpo7uxsw5wne5jocv9yhmoe',
                        name: 'fallback_chains_pkey',
                        unique: true,
                        fieldIds: ['1l0tyeqlfrobz65otktl8k3tn'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '39vxyz91j40mtzxor07seyp8o',
                name: 'fallback_steps',
                schema: 'public',
                x: 500,
                y: 600,
                fields: [
                    {
                        id: 'jj2mwv1x0fqb5bk0mz7twbhic',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'fe001lnpeky15l5a0cgyva1ir',
                        name: 'chain_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4vo6h9xtlxagusmu7ztvusys1',
                        name: 'model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9aqqnujtmsrp74tl4u9pfhi61',
                        name: 'step_order',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7tfwgt7op264r7d1773cjvbyp',
                        name: 'timeout_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '10000',
                        createdAt: now,
                    },
                    {
                        id: 'fzr4p1163mqrkzimk8vzj1zcy',
                        name: 'retry_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '1',
                        createdAt: now,
                    },
                    {
                        id: 'acplpbp75jua0l1md0wvelsjr',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'hrijt5zz4j0ujrypq0daroidl',
                        name: 'fallback_steps_pkey',
                        unique: true,
                        fieldIds: ['jj2mwv1x0fqb5bk0mz7twbhic'],
                        createdAt: now,
                    },
                    {
                        id: 'cu4l6kstwvrja9f8b6ahj6kl6',
                        name: 'idx_fallback_steps_chain',
                        unique: false,
                        fieldIds: [
                            'fe001lnpeky15l5a0cgyva1ir',
                            '9aqqnujtmsrp74tl4u9pfhi61',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'r4cc298b7ahz7fafcoauix0h1',
                name: 'rate_limits',
                schema: 'public',
                x: 900,
                y: 600,
                fields: [
                    {
                        id: 'f488sshzox79n6c7i8kwsmd6m',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'jw2yztylpehftwwhvn2bv0ehs',
                        name: 'api_key_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3yf6xj1l5n9612yeymajr6lb1',
                        name: 'model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x86xo6wo5a3760hoqtsxp5mzx',
                        name: 'window_seconds',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '60',
                        createdAt: now,
                    },
                    {
                        id: 'lnaljy4yoo04uyxttmnjwoih7',
                        name: 'max_requests',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0db3l0tb11meo28lskucwkpum',
                        name: 'max_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ee7gpujjjwho2n45jw6gssr7g',
                        name: 'current_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '45k289ua64x3y38yyzns7uzmr',
                        name: 'window_start',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'vsjjfq200f2ugt5mgatd1srv2',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '51v5k8nelwubhmdgrf1vkmiz1',
                        name: 'rate_limits_pkey',
                        unique: true,
                        fieldIds: ['f488sshzox79n6c7i8kwsmd6m'],
                        createdAt: now,
                    },
                    {
                        id: '5u0ujxeg93c47ahih1wm7hmln',
                        name: 'idx_rate_limits_key',
                        unique: false,
                        fieldIds: ['jw2yztylpehftwwhvn2bv0ehs'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '33xy0zlgw7myqxh80ehnqli1d',
                name: 'cache_entries',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: '699fvhtw5240gy6cu56q7eept',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'ao95ze7xomyw675j1o5rguxk4',
                        name: 'cache_key',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: '676alfsvd92zzta2tgpr5m0p3',
                        name: 'model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3vt0m1422xvzuiv1dmo87re3e',
                        name: 'request_hash',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: 'c4oqxykyuzuzw8tj2po56zdul',
                        name: 'response_body',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jj9avug38k8mqfkthd0fdg3bp',
                        name: 'input_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'h5qh8aflhmdnrokt7e0hlcsrb',
                        name: 'output_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'c5nkq9014qckvs024lir7pe9n',
                        name: 'ttl_seconds',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '3600',
                        createdAt: now,
                    },
                    {
                        id: 'lf7d04vqayv8xreh15wb2xtvl',
                        name: 'hit_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'jj1ukcbrc2wes7fmn1ho4ouh4',
                        name: 'expires_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'x1iih9rwdqdg4yyygmvvlqe7w',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sca15yg516jza9hyroiebzv6e',
                        name: 'cache_entries_pkey',
                        unique: true,
                        fieldIds: ['699fvhtw5240gy6cu56q7eept'],
                        createdAt: now,
                    },
                    {
                        id: 'a8hxjlrxyl0l1q9ta8cj8r3xw',
                        name: 'idx_cache_entries_expires',
                        unique: false,
                        fieldIds: ['jj1ukcbrc2wes7fmn1ho4ouh4'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'x5x3oaykezswhlrzkaj97srcl',
                name: 'request_logs',
                schema: 'public',
                x: 100,
                y: 1100,
                fields: [
                    {
                        id: 'gelelbq8awfa8vta31zfxfk1f',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'iefai7tn9bbjetvsc85sfbinq',
                        name: 'api_key_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'lpvg2jvakgqdtpk21qs37d2pc',
                        name: 'model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fukmlugujpfydj2pvl1031b21',
                        name: 'provider_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gwkft9j5q6liicncsvu2skplw',
                        name: 'request_method',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '10',
                        default: "'POST'",
                        createdAt: now,
                    },
                    {
                        id: '9qh75upj05lwm8jrxwhxcumu0',
                        name: 'request_path',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vti2mvjcp7wyy01qcrcv94bsz',
                        name: 'status_code',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nsuag23idrapixb3o6jp9ptba',
                        name: 'input_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ocd0tbx83ss5figcmscm48ln2',
                        name: 'output_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'op0p62om1ickj9wf5zetmxgjj',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8b6rwurvg2o86n513i61usp9t',
                        name: 'cost_cents',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        createdAt: now,
                    },
                    {
                        id: 'dhpojg9a35ox9r8kwisvct8tx',
                        name: 'cache_hit',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 't7cnfgkdgkwilccb3ow9nk44m',
                        name: 'error_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'xyj7hp803kwfglwuu2isqger2',
                        name: 'error_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '44a110e9uz0u45w3e6wki1g0i',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: '6azyv2jpfrvr8phy3q9y7eo7d',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bkxj8p7d3yf1ff3fi5ee0havw',
                        name: 'request_logs_pkey',
                        unique: true,
                        fieldIds: ['gelelbq8awfa8vta31zfxfk1f'],
                        createdAt: now,
                    },
                    {
                        id: '5bmexb8watyz5ksn2j0ossuha',
                        name: 'idx_request_logs_key',
                        unique: false,
                        fieldIds: ['iefai7tn9bbjetvsc85sfbinq'],
                        createdAt: now,
                    },
                    {
                        id: '1jgm68brtqj9u7yxno43sa98o',
                        name: 'idx_request_logs_created',
                        unique: false,
                        fieldIds: ['6azyv2jpfrvr8phy3q9y7eo7d'],
                        createdAt: now,
                    },
                ],
                color: '#ffcc5c',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '9nvcx1fg9un8utbpu2qx7ii4k',
                name: 'cost_tracking',
                schema: 'public',
                x: 500,
                y: 1100,
                fields: [
                    {
                        id: '600mvegbq1naeqdgfv5s1ez5x',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '1xmrzaprq3eiaaaxmqdrmbn4o',
                        name: 'api_key_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'pt38zl6xe4g1gu8h09lkhe6zt',
                        name: 'model_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'tciq9tez08qp63exabayayvnn',
                        name: 'period_start',
                        type: {
                            id: 'date',
                            name: 'date',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jltgldd311cz5srtqevrr4wby',
                        name: 'period_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '10',
                        default: "'daily'",
                        createdAt: now,
                    },
                    {
                        id: 'wkrlktk9ocu48gdior8fx76jm',
                        name: 'total_requests',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '013hch32nqaxyxfrkbmikotzg',
                        name: 'total_input_tokens',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'jjzebq3hrummfokag0r6exr21',
                        name: 'total_output_tokens',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '32589ok1odcsvmyy3dvlauxr4',
                        name: 'total_cost_cents',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        precision: 12,
                        scale: 4,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'gbzy8eu9tg91pahra75vrobhi',
                        name: 'cache_hits',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'vvekmtkn1tthq87ap90zhg7hk',
                        name: 'errors',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '5qd5vivjq9zxm2us5ujdu5zm6',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '3oo3gtoxp4z2vxydz0evoyo50',
                        name: 'cost_tracking_pkey',
                        unique: true,
                        fieldIds: ['600mvegbq1naeqdgfv5s1ez5x'],
                        createdAt: now,
                    },
                    {
                        id: 'ixif1wmnr3qx8mmn94ysbvs6o',
                        name: 'cost_tracking_api_key_id_model_id_period_start_period_type_unique',
                        unique: true,
                        fieldIds: [
                            '1xmrzaprq3eiaaaxmqdrmbn4o',
                            'pt38zl6xe4g1gu8h09lkhe6zt',
                            'tciq9tez08qp63exabayayvnn',
                            'jltgldd311cz5srtqevrr4wby',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'lnwx6bnq4yn1355wz7802cf4m',
                        name: 'idx_cost_tracking_period',
                        unique: false,
                        fieldIds: [
                            'tciq9tez08qp63exabayayvnn',
                            'jltgldd311cz5srtqevrr4wby',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#5ce1e6',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'xtekl8gimh3pgr5d0q2vfs9n4',
                name: 'models_provider_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                targetTableId: 'd86l4o08l6u4ahnz359c9jt57',
                sourceFieldId: '39iynubmd70osz71nlfg2g4us',
                targetFieldId: 'rc0cb77khl4nisoa2wb4dn2g6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'lks5dj3zxw0rnd88xexhx1iaj',
                name: 'api_keys_provider_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'lhonywx5ymd5553yxxse3xgx2',
                targetTableId: 'd86l4o08l6u4ahnz359c9jt57',
                sourceFieldId: 'rkqr3ii3r1ok9wttndgs6gr0b',
                targetFieldId: 'rc0cb77khl4nisoa2wb4dn2g6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '13jkff9kfwhrc62jimr2ulr21',
                name: 'routing_rules_target_provider_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tc8u3dcs5ycy6q5wovymdyr0e',
                targetTableId: 'd86l4o08l6u4ahnz359c9jt57',
                sourceFieldId: 'cw393oxwnwyb9aax3d4k8b2f3',
                targetFieldId: 'rc0cb77khl4nisoa2wb4dn2g6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ohf77gcn5ajdfgrogqt8d904o',
                name: 'routing_rules_target_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'tc8u3dcs5ycy6q5wovymdyr0e',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: 'vg3v2hvv6nnokncc2xut65zmb',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '0phpwwg6dsbu6aq9w0130mijl',
                name: 'fallback_chains_primary_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'md438ung1shwj1i4ck38kf346',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: 'u26myr33mk5yrugczt9bblao6',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'dui6iqwfbyuyjdkh25v6x3iek',
                name: 'fallback_steps_chain_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '39vxyz91j40mtzxor07seyp8o',
                targetTableId: 'md438ung1shwj1i4ck38kf346',
                sourceFieldId: 'fe001lnpeky15l5a0cgyva1ir',
                targetFieldId: '1l0tyeqlfrobz65otktl8k3tn',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'd29q8o2lu302iz8mjmqjm22tj',
                name: 'fallback_steps_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '39vxyz91j40mtzxor07seyp8o',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: '4vo6h9xtlxagusmu7ztvusys1',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'eldnspznjopo8m92exq4gzpol',
                name: 'rate_limits_api_key_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'r4cc298b7ahz7fafcoauix0h1',
                targetTableId: 'lhonywx5ymd5553yxxse3xgx2',
                sourceFieldId: 'jw2yztylpehftwwhvn2bv0ehs',
                targetFieldId: 'b89or8idtjp66bipd1f6ah9rp',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '2lapr4iqpxmxjych14w1w3ay5',
                name: 'rate_limits_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'r4cc298b7ahz7fafcoauix0h1',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: '3yf6xj1l5n9612yeymajr6lb1',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hwkp5xzm6pw35geg1lfvkvqnl',
                name: 'cache_entries_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '33xy0zlgw7myqxh80ehnqli1d',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: '676alfsvd92zzta2tgpr5m0p3',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'h14s5b6f49x2exvlta4a8jmk5',
                name: 'request_logs_api_key_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'x5x3oaykezswhlrzkaj97srcl',
                targetTableId: 'lhonywx5ymd5553yxxse3xgx2',
                sourceFieldId: 'iefai7tn9bbjetvsc85sfbinq',
                targetFieldId: 'b89or8idtjp66bipd1f6ah9rp',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'iclmd7j52xu2uycva0wwe76ll',
                name: 'request_logs_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'x5x3oaykezswhlrzkaj97srcl',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: 'lpvg2jvakgqdtpk21qs37d2pc',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fddmg9rcltekxuxd3r7r0h1i6',
                name: 'request_logs_provider_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'x5x3oaykezswhlrzkaj97srcl',
                targetTableId: 'd86l4o08l6u4ahnz359c9jt57',
                sourceFieldId: 'fukmlugujpfydj2pvl1031b21',
                targetFieldId: 'rc0cb77khl4nisoa2wb4dn2g6',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '88qwvq2vadlume2ikl09cfszo',
                name: 'cost_tracking_api_key_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '9nvcx1fg9un8utbpu2qx7ii4k',
                targetTableId: 'lhonywx5ymd5553yxxse3xgx2',
                sourceFieldId: '1xmrzaprq3eiaaaxmqdrmbn4o',
                targetFieldId: 'b89or8idtjp66bipd1f6ah9rp',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ovuq60rej0lv2sxy17ax7fi50',
                name: 'cost_tracking_model_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '9nvcx1fg9un8utbpu2qx7ii4k',
                targetTableId: 'lhokeefo2ecg6oxys06d5rxqb',
                sourceFieldId: 'pt38zl6xe4g1gu8h09lkhe6zt',
                targetFieldId: '6ppqm28gbgftnwvfylnu1ztok',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
