import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/mcp-registry.png';
import imageDark from '@/assets/templates/mcp-registry-dark.png';

const now = Date.now();

export const mcpRegistryDb: Template = {
    slug: 'mcp-registry',
    name: 'MCP Server Registry',
    shortDescription:
        'MCP server registry with tools, resources, and health checks',
    description:
        'Discover, connect, and monitor Model Context Protocol servers with tools, resources, and prompts',
    image,
    imageDark,
    tags: ['Postgres', 'AI', 'MCP'],
    featured: true,
    diagram: {
        id: 'mcp_registry_db',
        name: 'mcp-registry',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: '1xm65haopafrhs9oyz2x0xwn2',
                name: 'servers',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'xiajtougkkfgpavg08fm4u0ni',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'wgxxddkcxsb8jm6sqe2s8x23h',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'secipmv3gqgqikjtz950m3amm',
                        name: 'slug',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'p4p90573l7j2wjcl19mimrpk3',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'aqktsqpkofi072m3kivj1szeh',
                        name: 'author',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '1vg5y2zxai0ik4jb7lafepi93',
                        name: 'repository_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ilflozieiv9bjec4j57d2wza4',
                        name: 'homepage_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1tbybrdxmpth1iucz7x8iyuab',
                        name: 'icon_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ljzziqoyeeiqhflm8a12gvzn4',
                        name: 'transport_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'stdio'",
                        createdAt: now,
                    },
                    {
                        id: 'gfe8n6uiaxjtvrq53slq8vwve',
                        name: 'is_verified',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'xoxe7qghgsvlwf1ow59s1m7lh',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'bkdzspjg95u9oqn7fsu7jio6m',
                        name: 'install_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'q94r8lafmaoygjwmbwtvbcos2',
                        name: 'star_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'vynq0p34v8587wqabqzukr01z',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'wfj2h2om05h8eqbmwq9brdn80',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'cx86p77rqc7o6l6mibnh2pb2m',
                        name: 'servers_pkey',
                        unique: true,
                        fieldIds: ['xiajtougkkfgpavg08fm4u0ni'],
                        createdAt: now,
                    },
                    {
                        id: 'x1v3e8qgn17jqkxahblflvf2j',
                        name: 'idx_servers_slug',
                        unique: false,
                        fieldIds: ['secipmv3gqgqikjtz950m3amm'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'nnamzirom5pukwtzn4exy6246',
                name: 'server_versions',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'sast43263o3mcmjgdo07uzfwu',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'rd0i5wn1fgyxmu4oumsimhcdt',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2lwbm1k47rcdld2vzb6on8qtj',
                        name: 'version',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'b776y3lshsl6hk51701r807hu',
                        name: 'mcp_protocol_version',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: 'jyey01xt24h9slj0ch89gp75q',
                        name: 'changelog',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5j6lhd5bj03rsc2802l9wo63o',
                        name: 'package_url',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gfg5bl3rua4hogpe5c6lumkku',
                        name: 'checksum',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: 'hv4cldlr8zh1h1bics8kpbpch',
                        name: 'is_latest',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: '5rhnabazdsfjz2hzpfwmtb6xt',
                        name: 'published_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'v2k10swhisxtl15k3aiq20299',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'w2ynj3hvyxdgoxhvamvf7igoq',
                        name: 'server_versions_pkey',
                        unique: true,
                        fieldIds: ['sast43263o3mcmjgdo07uzfwu'],
                        createdAt: now,
                    },
                    {
                        id: 'fvhmgkr13re599c7faxz87ynr',
                        name: 'server_versions_server_id_version_unique',
                        unique: true,
                        fieldIds: [
                            'rd0i5wn1fgyxmu4oumsimhcdt',
                            '2lwbm1k47rcdld2vzb6on8qtj',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'm6d1ydasz9e9ejilpvb6pokds',
                        name: 'idx_server_versions_server',
                        unique: false,
                        fieldIds: ['rd0i5wn1fgyxmu4oumsimhcdt'],
                        createdAt: now,
                    },
                    {
                        id: 'rae1undem3hemow1jjygor491',
                        name: 'idx_server_versions_latest',
                        unique: false,
                        fieldIds: [
                            'rd0i5wn1fgyxmu4oumsimhcdt',
                            'hv4cldlr8zh1h1bics8kpbpch',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '66yi4xjnxkk6qpl48u7arx1mv',
                name: 'tools',
                schema: 'public',
                x: 900,
                y: 100,
                fields: [
                    {
                        id: '0dwxk8zovp39lvoznecwdbsrq',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '24h3lx1wnjw8vydbwh9d1peup',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 's22tnonftbgs6ylopx5od9cxe',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'pjjwjcgi1v2vwn7mske2flm8e',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i4v4h8mt26h3dv8qknk5hdpvk',
                        name: 'input_schema',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gm6slz0az7r7cfoi7bx9x6d32',
                        name: 'output_schema',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kqy5jiukcj4z02sql5hegfnwl',
                        name: 'is_destructive',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'rf9k5uy81ml4zq573xeooqwvj',
                        name: 'requires_confirmation',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'sg5i19drjraj9r036lde3thku',
                        name: 'example_input',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0115y2t50y1i51aobxvwgqud4',
                        name: 'example_output',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'q232godhhd4k44rwrbtwar6d6',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5r6l6xy5ha6fwsjxx3wwbleib',
                        name: 'tools_pkey',
                        unique: true,
                        fieldIds: ['0dwxk8zovp39lvoznecwdbsrq'],
                        createdAt: now,
                    },
                    {
                        id: 'mqhvokd82vpxn2f1unuv7dd4u',
                        name: 'tools_server_id_name_unique',
                        unique: true,
                        fieldIds: [
                            '24h3lx1wnjw8vydbwh9d1peup',
                            's22tnonftbgs6ylopx5od9cxe',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '140vi774sct2a4q9a85jsflzg',
                        name: 'idx_tools_server',
                        unique: false,
                        fieldIds: ['24h3lx1wnjw8vydbwh9d1peup'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'zn4m7an8l4kd7q5l1b16msw25',
                name: 'resources',
                schema: 'public',
                x: 1300,
                y: 100,
                fields: [
                    {
                        id: 'ok6efp0kuzdybk8enmr7qt196',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'ycp967qt0wqeo47ynna39d6a5',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'n1c3lxybklnhpkqtqwmcy346x',
                        name: 'uri_template',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'uws85i5fekzv6fv3bwootvstr',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'y9anegextncdtftn0kwsxhcgy',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'xfah0cpspukrea9lkp9c698gm',
                        name: 'mime_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'gxqx16lpvk4681u44dnsouqd9',
                        name: 'is_dynamic',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: '0o5bjlw01djzurf6c1pg492ki',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '9x1sk83adkzx4pnc2d04hrfo3',
                        name: 'resources_pkey',
                        unique: true,
                        fieldIds: ['ok6efp0kuzdybk8enmr7qt196'],
                        createdAt: now,
                    },
                    {
                        id: 'g3oy59zs0n7k6s1d3mqzphcvg',
                        name: 'resources_server_id_uri_template_unique',
                        unique: true,
                        fieldIds: [
                            'ycp967qt0wqeo47ynna39d6a5',
                            'n1c3lxybklnhpkqtqwmcy346x',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '337hyn9e5pl5hz5f16hl2i0jp',
                        name: 'idx_resources_server',
                        unique: false,
                        fieldIds: ['ycp967qt0wqeo47ynna39d6a5'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6in7ls0x45tkr543fttdnm9pe',
                name: 'prompts',
                schema: 'public',
                x: 100,
                y: 600,
                fields: [
                    {
                        id: '24t1krbanls7l2g1o4zq0ccsv',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '78chyjubot7qexaewu2ynxhhp',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bqt6601ujbna82iijaurtt8vu',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'yoecfksldeaomnzko79c5saue',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j4y1u94yvhp3ljyje70spzesp',
                        name: 'arguments',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'[]'",
                        createdAt: now,
                    },
                    {
                        id: 'k9lp8tjc5g4c2v1ndk4fjane7',
                        name: 'example_output',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'j4yeoyibldyow0m6v9a8spydd',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '4snkebnqlrllv3abdqi5gbkgl',
                        name: 'prompts_pkey',
                        unique: true,
                        fieldIds: ['24t1krbanls7l2g1o4zq0ccsv'],
                        createdAt: now,
                    },
                    {
                        id: 'c4vij2pkd1yvqngw35yt1nlp8',
                        name: 'prompts_server_id_name_unique',
                        unique: true,
                        fieldIds: [
                            '78chyjubot7qexaewu2ynxhhp',
                            'bqt6601ujbna82iijaurtt8vu',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'osujlzrqfypejokbptae6ysa7',
                        name: 'idx_prompts_server',
                        unique: false,
                        fieldIds: ['78chyjubot7qexaewu2ynxhhp'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'prw2lncbrpbolr9ppu55tc0in',
                name: 'connection_configs',
                schema: 'public',
                x: 500,
                y: 600,
                fields: [
                    {
                        id: 'lfepmu1wdxsilb38wkdp4yja8',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'q5tioh7twmu35v6idxc5sfaa3',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'gmcd8yg8ktdpjkt3udgzpxb0g',
                        name: 'user_id',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '56k9t81i6gs665bprl7cl9bq6',
                        name: 'config_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        default: "'default'",
                        createdAt: now,
                    },
                    {
                        id: 'x3cqfol726fh6vx2w43c1wxef',
                        name: 'transport_config',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sdtxcia66qee8wdgrczl523rx',
                        name: 'env_vars',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'on8uug9pfocnwkobgpx9sgypv',
                        name: 'auto_connect',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: '0owe8tfj029giarp9owbxs2vo',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'uevvbd931vug8xewkj2yeymm7',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'g3fq6331dw04ppg9a9jxmq854',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'e6y28bq5gejxmpxrxlyw85ytu',
                        name: 'connection_configs_pkey',
                        unique: true,
                        fieldIds: ['lfepmu1wdxsilb38wkdp4yja8'],
                        createdAt: now,
                    },
                    {
                        id: 'ghdsd0hjng7trsa85pcicydwl',
                        name: 'idx_connection_configs_server',
                        unique: false,
                        fieldIds: ['q5tioh7twmu35v6idxc5sfaa3'],
                        createdAt: now,
                    },
                    {
                        id: 'rnhnsnp2j2xo84ktblb8jeysk',
                        name: 'idx_connection_configs_user',
                        unique: false,
                        fieldIds: ['gmcd8yg8ktdpjkt3udgzpxb0g'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '1doh3agyo6rn7obl7x630u0o2',
                name: 'permissions',
                schema: 'public',
                x: 900,
                y: 600,
                fields: [
                    {
                        id: 'dma1yifd7qi1le4zfiz2stnc9',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'zuspxaugsi55ge9j354vq17fq',
                        name: 'connection_config_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'pipvo5ookq28c6u70paj50vlr',
                        name: 'tool_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'lsjs9izckqlcroowtdqiyt8ql',
                        name: 'resource_uri_pattern',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1ytd01kpgha06494q4s6k4z6b',
                        name: 'permission_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'allow'",
                        createdAt: now,
                    },
                    {
                        id: '5tcnuvdozido826f9q3mkx7wt',
                        name: 'requires_approval',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'zwf5obyfkg1i4g6feeo3pg4ys',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2u9r3t385sfv424poamgxg5q0',
                        name: 'permissions_pkey',
                        unique: true,
                        fieldIds: ['dma1yifd7qi1le4zfiz2stnc9'],
                        createdAt: now,
                    },
                    {
                        id: 'f2lrtbrf79hmiex3vuhdk8rxa',
                        name: 'idx_permissions_config',
                        unique: false,
                        fieldIds: ['zuspxaugsi55ge9j354vq17fq'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'vazgmu6no51pkwpsbwyagosyg',
                name: 'usage_logs',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: 'l49eixlkpajnvdbv7ylzbj7ok',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '54365by8vz412n8xlr5f155jc',
                        name: 'connection_config_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '74tin1e6b9rjc7qa9hdno608i',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'dzx1a4st9s98mgd6h7snvattc',
                        name: 'request_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: '3tzn96sjvgcso1hr3o51mcdfe',
                        name: 'tool_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 't0czsfxvnil7nhhodq6jrdjvl',
                        name: 'resource_uri',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dyoxrc0czrqrgnpmrjmui2hll',
                        name: 'prompt_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'jt2nqlvhas0fewea25qybr6ls',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: 'kg68zoo0mmnatdp4hryak7sf9',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '8tmacv0neghzh6zfft3pc928h',
                        name: 'error_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'r3hxpfk40gtg5gq8dt7louqvb',
                        name: 'request_metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: '9cn59l1andld36z8rgbxjt042',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'oobfkp6rjbjulsffcmjug4hza',
                        name: 'usage_logs_pkey',
                        unique: true,
                        fieldIds: ['l49eixlkpajnvdbv7ylzbj7ok'],
                        createdAt: now,
                    },
                    {
                        id: 'q3v0d8vlkgu24wk4rf4baj7ng',
                        name: 'idx_usage_logs_config',
                        unique: false,
                        fieldIds: ['54365by8vz412n8xlr5f155jc'],
                        createdAt: now,
                    },
                    {
                        id: 'zct43hp1isytbvkannh15os3z',
                        name: 'idx_usage_logs_server',
                        unique: false,
                        fieldIds: ['74tin1e6b9rjc7qa9hdno608i'],
                        createdAt: now,
                    },
                    {
                        id: 'l7kwcjfs0te1z26ixaro5ls3v',
                        name: 'idx_usage_logs_created',
                        unique: false,
                        fieldIds: ['9cn59l1andld36z8rgbxjt042'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '3r8a7s0tj5c7b3yw22libi5yw',
                name: 'health_checks',
                schema: 'public',
                x: 100,
                y: 1100,
                fields: [
                    {
                        id: 'kmnrckakzz3jqihluu0u621hi',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '8uhb39vou6lun93mzoggc76oa',
                        name: 'server_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mc50wiz7axef0v7bh71cam5z6',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: 'ugbuadrp3sr70johus5u3rxei',
                        name: 'response_time_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'oh8a75pv9a1du50u3k4ayym6k',
                        name: 'tool_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qs5vdtfd4m3j0c3dg494epkh8',
                        name: 'resource_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3dxpcesdfygk1jhkta8iwywmc',
                        name: 'prompt_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'esc4fzd3o72l9ja4u1q15h3fg',
                        name: 'protocol_version',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: '1d1off0rj4a1dk7pewly4b82p',
                        name: 'error_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0jwpvkbwnk9ch6wnevekd74ea',
                        name: 'checked_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: '5o3jbk4mayv21jxr1wqo9slg5',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '9y7zcvyobxomr1cwhpc0x9w97',
                        name: 'health_checks_pkey',
                        unique: true,
                        fieldIds: ['kmnrckakzz3jqihluu0u621hi'],
                        createdAt: now,
                    },
                    {
                        id: 'a3ow0mazqxgkn06u8e2b82ov6',
                        name: 'idx_health_checks_server',
                        unique: false,
                        fieldIds: ['8uhb39vou6lun93mzoggc76oa'],
                        createdAt: now,
                    },
                    {
                        id: '3xrv7kkq3hutx85fkfzcffxzb',
                        name: 'idx_health_checks_checked',
                        unique: false,
                        fieldIds: ['0jwpvkbwnk9ch6wnevekd74ea'],
                        createdAt: now,
                    },
                ],
                color: '#ffcc5c',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'swhhziwtbv7h256lu00qp0dna',
                name: 'server_versions_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'nnamzirom5pukwtzn4exy6246',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: 'rd0i5wn1fgyxmu4oumsimhcdt',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'e9s2gva98q6mv0qd7v4yx2ba2',
                name: 'tools_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '66yi4xjnxkk6qpl48u7arx1mv',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: '24h3lx1wnjw8vydbwh9d1peup',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'wsk106imry4ellxhmxigfhtxj',
                name: 'resources_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'zn4m7an8l4kd7q5l1b16msw25',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: 'ycp967qt0wqeo47ynna39d6a5',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '1yqsprvpjbaeipskf932jn69c',
                name: 'prompts_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6in7ls0x45tkr543fttdnm9pe',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: '78chyjubot7qexaewu2ynxhhp',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'yl8x9zn4lczzo1yuaesh67eeb',
                name: 'connection_configs_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'prw2lncbrpbolr9ppu55tc0in',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: 'q5tioh7twmu35v6idxc5sfaa3',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'sfkjxrpbqdj6bf5enjqqwod14',
                name: 'permissions_connection_config_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '1doh3agyo6rn7obl7x630u0o2',
                targetTableId: 'prw2lncbrpbolr9ppu55tc0in',
                sourceFieldId: 'zuspxaugsi55ge9j354vq17fq',
                targetFieldId: 'lfepmu1wdxsilb38wkdp4yja8',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '1lvkcg76gik2p4c3w3j1ntvq2',
                name: 'usage_logs_connection_config_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vazgmu6no51pkwpsbwyagosyg',
                targetTableId: 'prw2lncbrpbolr9ppu55tc0in',
                sourceFieldId: '54365by8vz412n8xlr5f155jc',
                targetFieldId: 'lfepmu1wdxsilb38wkdp4yja8',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'eb23a0v87epovum4a0axg585n',
                name: 'usage_logs_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'vazgmu6no51pkwpsbwyagosyg',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: '74tin1e6b9rjc7qa9hdno608i',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'z837vz6z34z22lcvfguml2h8x',
                name: 'health_checks_server_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '3r8a7s0tj5c7b3yw22libi5yw',
                targetTableId: '1xm65haopafrhs9oyz2x0xwn2',
                sourceFieldId: '8uhb39vou6lun93mzoggc76oa',
                targetFieldId: 'xiajtougkkfgpavg08fm4u0ni',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
