import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/multi-agent.png';
import imageDark from '@/assets/templates/multi-agent-dark.png';

const now = Date.now();

export const multiAgentDb: Template = {
    slug: 'multi-agent',
    name: 'Multi-Agent Orchestration',
    shortDescription: 'Multi-agent system with tools, handoffs, and memory',
    description:
        'Agent configs, conversations, tool calls, handoffs, and execution traces for multi-agent systems',
    image,
    imageDark,
    tags: ['Postgres', 'AI', 'Agents'],
    featured: true,
    diagram: {
        id: 'multi_agent_db',
        name: 'multi-agent',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: 'u4ql8ki8g70dlevbuiy80qkjn',
                name: 'agents',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'yfrd2bp8eje0m27fwu2i2v7rj',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'cc7z7l9ef0evus9n1u9x93z7k',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'rqifk9j0zmse5ucmvok0a6lng',
                        name: 'slug',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'by32x0m5x57pqtyzr5twlgscg',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'i0tc5vl67ar2lagx1nslx8ijt',
                        name: 'system_prompt',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sobqokt5663w9sac4tqzlbzhe',
                        name: 'model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: '7ufn0wm7xgh4uvw4v6txwje6f',
                        name: 'temperature',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 3,
                        scale: 2,
                        default: '0.7',
                        createdAt: now,
                    },
                    {
                        id: '02q4blnq4x6nu447pwh2lbn79',
                        name: 'max_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '4096',
                        createdAt: now,
                    },
                    {
                        id: 'yqzzhp6h0vqll64tvi0odf3b2',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'eb7iaqcqd2pkns3gdsw73si5f',
                        name: 'created_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '7lg7jae0ah6lpzhgbz7asc9na',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'nkcqch89sqm7v0xnnuk0lfjty',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 't3annk27109cp1yjhfqkykeul',
                        name: 'agents_pkey',
                        unique: true,
                        fieldIds: ['yfrd2bp8eje0m27fwu2i2v7rj'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ac20wdh9ri6big5k1hsg9025c',
                name: 'agent_configs',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'o26yxkypcxewvmfslcgy0oo5s',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'e9qywaqkzyr4wl1mc0lz66xv3',
                        name: 'agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2e95jxxcgmvxiifp4x8yubmz8',
                        name: 'version',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'm7qok2mbjwfdrdnm6a9c3yfrb',
                        name: 'config',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '0emq62ngjopuw3nwcerwx4676',
                        name: 'allowed_tools',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'[]'",
                        createdAt: now,
                    },
                    {
                        id: 'ge72o90kuedl5zyduesoopjbq',
                        name: 'allowed_handoff_targets',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'[]'",
                        createdAt: now,
                    },
                    {
                        id: '4wjzcuwfhwbizzzntu45zvmck',
                        name: 'max_turns',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '25',
                        createdAt: now,
                    },
                    {
                        id: 'is1cp4ymgp7vokflntwpi4wm4',
                        name: 'timeout_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '120000',
                        createdAt: now,
                    },
                    {
                        id: '8nsu5fflh7rrq0rezft5ckyel',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'z39bf4taon7v02vrbf1mul4fw',
                        name: 'activated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nbaqjuzn2wkfel47ypixkkxvn',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'hrakglrscsz7m6h1gvnuxg2ql',
                        name: 'agent_configs_pkey',
                        unique: true,
                        fieldIds: ['o26yxkypcxewvmfslcgy0oo5s'],
                        createdAt: now,
                    },
                    {
                        id: 'bn2893l1s2uzz9l71fjxpzd28',
                        name: 'agent_configs_agent_id_version_unique',
                        unique: true,
                        fieldIds: [
                            'e9qywaqkzyr4wl1mc0lz66xv3',
                            '2e95jxxcgmvxiifp4x8yubmz8',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'r8z66guzyvwps319nlxma0nml',
                        name: 'idx_agent_configs_agent',
                        unique: false,
                        fieldIds: ['e9qywaqkzyr4wl1mc0lz66xv3'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '27ao9p7wykq3xgr0a3hd7f2nk',
                name: 'tool_registry',
                schema: 'public',
                x: 900,
                y: 100,
                fields: [
                    {
                        id: 'odv6wj8shgctecibdvjgres3c',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'wnk6bm6chat3ydg670i6oea53',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'ybk468lh26zbiq8zjo2nug8uj',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'z9qi5gvxlcb8zlrz28dsp4jpc',
                        name: 'input_schema',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5zp4igfluet9jzwcq44h2a5iq',
                        name: 'output_schema',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'vco9zzdiibncma01b60b3gync',
                        name: 'handler_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        default: "'function'",
                        createdAt: now,
                    },
                    {
                        id: 'htwk4oj3h9yuqz88ycjsxnfix',
                        name: 'handler_config',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: '605bsmkyfxm7asn3rdou0f431',
                        name: 'requires_confirmation',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'vyouxi6e1f2akwymjb0nldelj',
                        name: 'timeout_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: '30000',
                        createdAt: now,
                    },
                    {
                        id: '9tzr1i2c8wh1pas02xqg3p7m5',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'xgpa2cfm2bb01a5uo3lr54zrq',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'dp6bz5xhk6mwqsmbhopwevcko',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'ozvmmbhvk4os5nq8q1w2pf7qt',
                        name: 'tool_registry_pkey',
                        unique: true,
                        fieldIds: ['odv6wj8shgctecibdvjgres3c'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'x7s3x6bwmdl8jcpefw0cuwgct',
                name: 'conversations',
                schema: 'public',
                x: 1300,
                y: 100,
                fields: [
                    {
                        id: 'eagzinl8l0h25jfdv89xyicgk',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'bh1jsogsc3chlg8vx50dgjjjq',
                        name: 'initial_agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bq3n11df1j789v52wlnrtuukl',
                        name: 'current_agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'abo69rxtgilajtm85su8juv4s',
                        name: 'user_id',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '7wzosyq4zn73tkkdi7wvgwzrs',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '500',
                        createdAt: now,
                    },
                    {
                        id: 'j659oik2if8tm537ykl19gv0a',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'active'",
                        createdAt: now,
                    },
                    {
                        id: '9sj0r3xihjmg5anze5g8dejv2',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'fw5vlxqpk37pgcjjvhm5vogn9',
                        name: 'total_turns',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'fpuxsrff5bmy64ji83szpva9j',
                        name: 'total_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'l3fht7dvv6chi6ecbto9qpd4f',
                        name: 'total_cost_cents',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'oyj8xn2ncg2t70kmz4ah4iuho',
                        name: 'started_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: '255f3lgnu6ayuju7pqb0b6j2o',
                        name: 'ended_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zjdk9l2pf77zf8dripxabp9h5',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'yhx4mpja3lugwhyjy7saawfr2',
                        name: 'conversations_pkey',
                        unique: true,
                        fieldIds: ['eagzinl8l0h25jfdv89xyicgk'],
                        createdAt: now,
                    },
                    {
                        id: 's3pxvulw2ak1iskhu2ji4qm1l',
                        name: 'idx_conversations_user',
                        unique: false,
                        fieldIds: ['abo69rxtgilajtm85su8juv4s'],
                        createdAt: now,
                    },
                    {
                        id: '01b1ml15rg5ecvixa4cbox0gb',
                        name: 'idx_conversations_status',
                        unique: false,
                        fieldIds: ['j659oik2if8tm537ykl19gv0a'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '2u0m207iifznz9bhqmmm5vzfv',
                name: 'turns',
                schema: 'public',
                x: 100,
                y: 600,
                fields: [
                    {
                        id: 'tb47co6du9zdnvfwu9py82cpt',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '3ijff3q4ib3e14nwpnzu6tg2y',
                        name: 'conversation_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'a114w6c3ieur34o6ss1bjyvr1',
                        name: 'agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '3vx15p0f0eg95pedcik0fhj3h',
                        name: 'turn_number',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ovi7awrkybzgld883ayzjr7ie',
                        name: 'role',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        createdAt: now,
                    },
                    {
                        id: 'ihvsad25yzk3v5y7lke6lw62z',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5pm2od6u4gxh9jx0qpth85qcw',
                        name: 'input_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'e9ff7qgeducyomwdd8ez8cz55',
                        name: 'output_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'avlv9l059he68fyan6yd09kmf',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x6spuc1z658shmfaokldnhw7h',
                        name: 'model_used',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'zllahdqbuc8x8drgq0l04r0io',
                        name: 'finish_reason',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: '2e28u3ftmq8fcugshvl8r3v6y',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'umjfbjfs5nepzfbgxuck8tgix',
                        name: 'turns_pkey',
                        unique: true,
                        fieldIds: ['tb47co6du9zdnvfwu9py82cpt'],
                        createdAt: now,
                    },
                    {
                        id: 'i75d49miy85dmxz4guyitimam',
                        name: 'idx_turns_conversation',
                        unique: false,
                        fieldIds: [
                            '3ijff3q4ib3e14nwpnzu6tg2y',
                            '3vx15p0f0eg95pedcik0fhj3h',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '11s7hp4lr4zl8hr3mrz83g6jt',
                        name: 'idx_turns_agent',
                        unique: false,
                        fieldIds: ['a114w6c3ieur34o6ss1bjyvr1'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6zqbjw2n0hahccm0sgxhnhfgw',
                name: 'tool_calls',
                schema: 'public',
                x: 500,
                y: 600,
                fields: [
                    {
                        id: 't49p3jt40enm8szzgsije9089',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'wc22xlqpkpgn1z7uhaiqr18io',
                        name: 'turn_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kxx6bspt311r5pw0uq2mxuqh2',
                        name: 'tool_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'nr5y7zxhf9v8vw2sl7sose061',
                        name: 'call_id',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'fe3mi2czk68vik1dzlzxheqxf',
                        name: 'input_args',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'imezwp4pird7ombp7ji3wwv1u',
                        name: 'output_result',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w8k7qrykl3stc7dnjh92adtvg',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'pending'",
                        createdAt: now,
                    },
                    {
                        id: '6txrukt8vfkkolf5n99cvkb2a',
                        name: 'error_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qzwvp48px5ot743bpqoj0oxna',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'hmask2cmtbeaalt1h4z612452',
                        name: 'confirmed_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '1u992lu9uoz63ln6g2ze3ig5g',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'hgfcna86yplkopey4inyq9yqi',
                        name: 'tool_calls_pkey',
                        unique: true,
                        fieldIds: ['t49p3jt40enm8szzgsije9089'],
                        createdAt: now,
                    },
                    {
                        id: '3y8yj3x97jxzog14w1g15i4yd',
                        name: 'idx_tool_calls_turn',
                        unique: false,
                        fieldIds: ['wc22xlqpkpgn1z7uhaiqr18io'],
                        createdAt: now,
                    },
                    {
                        id: 'yg3tzxgm27o8qwasp4craukmw',
                        name: 'idx_tool_calls_tool',
                        unique: false,
                        fieldIds: ['kxx6bspt311r5pw0uq2mxuqh2'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'cqo8tfuchh6vbg9wv39r5zuxn',
                name: 'handoffs',
                schema: 'public',
                x: 900,
                y: 600,
                fields: [
                    {
                        id: 'xhb54yx84vkbqv1or079o1uzj',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '1d4y0pat0axixb5izh5plc53i',
                        name: 'conversation_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2ysoe5jx25qodmk2um5nve06s',
                        name: 'from_agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'i1b2gdwx68ljqxd4zjefo7rb4',
                        name: 'to_agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'o6hai73ywe6mqe5k9fwp6wciw',
                        name: 'from_turn_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ux9pgrmjzue8k5fkzbzpxar8d',
                        name: 'reason',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'zjnbtoo15vjq0jm0qcryovy2e',
                        name: 'context_summary',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ilp8sp50zwcjsxmj79c4jtvqx',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'jsgjgmchr3f7yrgfdybfgnpzv',
                        name: 'handoffs_pkey',
                        unique: true,
                        fieldIds: ['xhb54yx84vkbqv1or079o1uzj'],
                        createdAt: now,
                    },
                    {
                        id: '36wxeafky154avpkgi7pjivig',
                        name: 'idx_handoffs_conversation',
                        unique: false,
                        fieldIds: ['1d4y0pat0axixb5izh5plc53i'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c39eqit9cabhedhu4rw2itoj4',
                name: 'execution_traces',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: '4bh2ptzj3ue20igqfvw0zmohh',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '26i6twm8d5ybfs3svh3xlb3p3',
                        name: 'conversation_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kl5pvftkxu2h9z65pay0ny3k4',
                        name: 'turn_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1mhreiw91qjx75zbg8n7klr0b',
                        name: 'trace_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: '4tqx19kt1rr6lr9d2ix2yrijl',
                        name: 'event_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '8y0ww7aza7oip21hbztrginq1',
                        name: 'event_data',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'vd08afonkdtrnnq4t86gadnrk',
                        name: 'parent_trace_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ps7rscm0rocw1tvz4jkp0qoao',
                        name: 'duration_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'x6f6j0fs3wvzfgi21bi7ehbnm',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'nw9mj1demthh3evvqvasu5z46',
                        name: 'execution_traces_pkey',
                        unique: true,
                        fieldIds: ['4bh2ptzj3ue20igqfvw0zmohh'],
                        createdAt: now,
                    },
                    {
                        id: 'znzy0v84zdpmgz8ao1q6rs73l',
                        name: 'idx_execution_traces_conversation',
                        unique: false,
                        fieldIds: ['26i6twm8d5ybfs3svh3xlb3p3'],
                        createdAt: now,
                    },
                    {
                        id: 'qm28kwgawkxqwyryp5xl8jdmd',
                        name: 'idx_execution_traces_parent',
                        unique: false,
                        fieldIds: ['vd08afonkdtrnnq4t86gadnrk'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xgn3u99wipz7cv6hh38koo63v',
                name: 'memory',
                schema: 'public',
                x: 100,
                y: 1100,
                fields: [
                    {
                        id: 'k3fyzqg08thcg1h0va2rohpur',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'ehr6etad2ag3dvsdwnyibnu9p',
                        name: 'agent_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mvbdj793udz1g3vmtyncamyv8',
                        name: 'conversation_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '01i4j61dujsn0m37mmusg66gb',
                        name: 'memory_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        default: "'episodic'",
                        createdAt: now,
                    },
                    {
                        id: '8p1pyn97bv75j8o5y4k3qpozi',
                        name: 'key',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '2zevpu36878ph9nq8exxlg1nt',
                        name: 'value',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bwu4hyvtaeuv403e0y1ytqb7t',
                        name: 'importance_score',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 5,
                        scale: 4,
                        default: '0.5',
                        createdAt: now,
                    },
                    {
                        id: 'beyspd3if2iuwxq6k7eu1kpxk',
                        name: 'access_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'ypgujvgidcy2omsk9zi92jxgx',
                        name: 'last_accessed_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'po7jy546zeoocyyr2f5dh0iy0',
                        name: 'expires_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mc0lmltqy6589qvrq6pg8eyee',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'baygbzyv0ll83drpr0s2xruzq',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'mlyy4g4cipdml4k520mxuh2ac',
                        name: 'memory_pkey',
                        unique: true,
                        fieldIds: ['k3fyzqg08thcg1h0va2rohpur'],
                        createdAt: now,
                    },
                    {
                        id: 'pum2meqso9hwp8fyxzs4c4k2p',
                        name: 'idx_memory_agent',
                        unique: false,
                        fieldIds: ['ehr6etad2ag3dvsdwnyibnu9p'],
                        createdAt: now,
                    },
                    {
                        id: 'qggthqaadhm8e2dg0gv2j3xdc',
                        name: 'idx_memory_conversation',
                        unique: false,
                        fieldIds: ['mvbdj793udz1g3vmtyncamyv8'],
                        createdAt: now,
                    },
                    {
                        id: 'a1h0llnkbygkjgss1jbmtjzmn',
                        name: 'idx_memory_key',
                        unique: false,
                        fieldIds: [
                            'ehr6etad2ag3dvsdwnyibnu9p',
                            '8p1pyn97bv75j8o5y4k3qpozi',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#ffcc5c',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'khocvcm4vnyqu6x2t0x5oyw3i',
                name: 'agent_configs_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ac20wdh9ri6big5k1hsg9025c',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'e9qywaqkzyr4wl1mc0lz66xv3',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6g2utte1rzshne67pokkgmt5i',
                name: 'conversations_initial_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'bh1jsogsc3chlg8vx50dgjjjq',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '4sf5la0akpgoyqbbxofbfkyfb',
                name: 'conversations_current_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'bq3n11df1j789v52wlnrtuukl',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'rgybyj851nm82yjdqagr4iq8q',
                name: 'turns_conversation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '2u0m207iifznz9bhqmmm5vzfv',
                targetTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                sourceFieldId: '3ijff3q4ib3e14nwpnzu6tg2y',
                targetFieldId: 'eagzinl8l0h25jfdv89xyicgk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fs0ms5ae15fttveffs70xgw80',
                name: 'turns_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '2u0m207iifznz9bhqmmm5vzfv',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'a114w6c3ieur34o6ss1bjyvr1',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '4qsau7rc9mybugbr3n3j1dhic',
                name: 'tool_calls_turn_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6zqbjw2n0hahccm0sgxhnhfgw',
                targetTableId: '2u0m207iifznz9bhqmmm5vzfv',
                sourceFieldId: 'wc22xlqpkpgn1z7uhaiqr18io',
                targetFieldId: 'tb47co6du9zdnvfwu9py82cpt',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vq60439t3hiuy8brmc69hez7d',
                name: 'tool_calls_tool_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6zqbjw2n0hahccm0sgxhnhfgw',
                targetTableId: '27ao9p7wykq3xgr0a3hd7f2nk',
                sourceFieldId: 'kxx6bspt311r5pw0uq2mxuqh2',
                targetFieldId: 'odv6wj8shgctecibdvjgres3c',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'tgaojsgjaibdp6b3ee0ryk93a',
                name: 'handoffs_conversation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'cqo8tfuchh6vbg9wv39r5zuxn',
                targetTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                sourceFieldId: '1d4y0pat0axixb5izh5plc53i',
                targetFieldId: 'eagzinl8l0h25jfdv89xyicgk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'vh8cjchk5p2jvag75yjp93hwj',
                name: 'handoffs_from_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'cqo8tfuchh6vbg9wv39r5zuxn',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: '2ysoe5jx25qodmk2um5nve06s',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '6zcyay52ixcnwnbumurf92d6z',
                name: 'handoffs_to_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'cqo8tfuchh6vbg9wv39r5zuxn',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'i1b2gdwx68ljqxd4zjefo7rb4',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'hoyzthwcwjwq06i63irzmiqz4',
                name: 'handoffs_from_turn_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'cqo8tfuchh6vbg9wv39r5zuxn',
                targetTableId: '2u0m207iifznz9bhqmmm5vzfv',
                sourceFieldId: 'o6hai73ywe6mqe5k9fwp6wciw',
                targetFieldId: 'tb47co6du9zdnvfwu9py82cpt',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ih89k51b1pct1decphsfrxzwn',
                name: 'execution_traces_conversation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c39eqit9cabhedhu4rw2itoj4',
                targetTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                sourceFieldId: '26i6twm8d5ybfs3svh3xlb3p3',
                targetFieldId: 'eagzinl8l0h25jfdv89xyicgk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'c4hbvj6l2kk1uuxrar3vsojij',
                name: 'execution_traces_turn_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c39eqit9cabhedhu4rw2itoj4',
                targetTableId: '2u0m207iifznz9bhqmmm5vzfv',
                sourceFieldId: 'kl5pvftkxu2h9z65pay0ny3k4',
                targetFieldId: 'tb47co6du9zdnvfwu9py82cpt',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '75adoyjbdfro2no4lufut8fd5',
                name: 'execution_traces_parent_trace_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c39eqit9cabhedhu4rw2itoj4',
                targetTableId: 'c39eqit9cabhedhu4rw2itoj4',
                sourceFieldId: 'vd08afonkdtrnnq4t86gadnrk',
                targetFieldId: '4bh2ptzj3ue20igqfvw0zmohh',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'p358ioxahdl3yh2drj3s9bcjp',
                name: 'memory_agent_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xgn3u99wipz7cv6hh38koo63v',
                targetTableId: 'u4ql8ki8g70dlevbuiy80qkjn',
                sourceFieldId: 'ehr6etad2ag3dvsdwnyibnu9p',
                targetFieldId: 'yfrd2bp8eje0m27fwu2i2v7rj',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ywgyvqextihpnnbt85rckmueu',
                name: 'memory_conversation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xgn3u99wipz7cv6hh38koo63v',
                targetTableId: 'x7s3x6bwmdl8jcpefw0cuwgct',
                sourceFieldId: 'mvbdj793udz1g3vmtyncamyv8',
                targetFieldId: 'eagzinl8l0h25jfdv89xyicgk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
