import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/prompt-management.png';
import imageDark from '@/assets/templates/prompt-management-dark.png';

const now = Date.now();

export const promptManagementDb: Template = {
    slug: 'prompt-management',
    name: 'Prompt Management',
    shortDescription: 'Prompt versioning, testing, and deployment pipeline',
    description:
        'Version, test, evaluate, and deploy prompts with full lifecycle management',
    image,
    imageDark,
    tags: ['Postgres', 'AI', 'Prompts'],
    featured: true,
    diagram: {
        id: 'prompt_management_db',
        name: 'prompt-management',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: 'b73lg4u2kasji7cy98jwy8a6b',
                name: 'prompts',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: '01cjrhomo149b9njbxj4yf9ec',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'kjdzqak0rnnhirfrpv62bvxrk',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'oeq99ci6m8ndkplthlwwmow0h',
                        name: 'slug',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '8pmwhufxvnhy6sahii3zuwrjl',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '4lx06pbexwjsnvi18zendrif4',
                        name: 'system_prompt',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'okbrhjy1c26u7j6ng8c8wn5va',
                        name: 'category',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'jc86tijru59s17j2futp7bw9x',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'eq6dsa8pu8t5ytvaa9k9pj9jp',
                        name: 'created_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'e3wg14vxfxeni1wzqabmdm59e',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'b4siqx32tiqrv5voqxtsycn0x',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'c23yrwuylhbd2pwst6h4jk2sq',
                        name: 'prompts_pkey',
                        unique: true,
                        fieldIds: ['01cjrhomo149b9njbxj4yf9ec'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '8wvmk64tgrtot2hfvduvesrlm',
                name: 'prompt_versions',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'scfr2vrulc7esjm0rwurz1xpb',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'fcj9ynw7bv5umbn6zz4i0oaju',
                        name: 'prompt_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2mynbi0gmpmp8c5svepai8k3n',
                        name: 'version',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'cvnphqz3a0w715i758mfc83a3',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vlps00ivm0al2psel9wjbreg0',
                        name: 'model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'qz8f474l68s0a8y5dqvbl8yuq',
                        name: 'temperature',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 3,
                        scale: 2,
                        createdAt: now,
                    },
                    {
                        id: 'nlobujwot6dsoq9c34rot4jzi',
                        name: 'max_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qxnwbtj1qf4wmgyebwmmrh37e',
                        name: 'stop_sequences',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'w15001fvn8te806s9cyfgtp28',
                        name: 'change_notes',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wcovj0knz9cte7zihrsyi8180',
                        name: 'is_published',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'false',
                        createdAt: now,
                    },
                    {
                        id: 'mqlw9kh3cqij6vez39onxbdzb',
                        name: 'published_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '3spa2q2mhrr8d4aumuv2du0re',
                        name: 'created_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'sr0rkzdsgn8yxdx1y7txtub6u',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'tiulg4udgp7ekouqh6rf59pzg',
                        name: 'prompt_versions_pkey',
                        unique: true,
                        fieldIds: ['scfr2vrulc7esjm0rwurz1xpb'],
                        createdAt: now,
                    },
                    {
                        id: 'otokbwaovw69ojtck7ed2a365',
                        name: 'prompt_versions_prompt_id_version_unique',
                        unique: true,
                        fieldIds: [
                            'fcj9ynw7bv5umbn6zz4i0oaju',
                            '2mynbi0gmpmp8c5svepai8k3n',
                        ],
                        createdAt: now,
                    },
                    {
                        id: 'wphml73f4awn68dv098me6ln6',
                        name: 'idx_prompt_versions_prompt',
                        unique: false,
                        fieldIds: ['fcj9ynw7bv5umbn6zz4i0oaju'],
                        createdAt: now,
                    },
                    {
                        id: 'adp7wvgw6v8b02qfcq1tgfbcq',
                        name: 'idx_prompt_versions_published',
                        unique: false,
                        fieldIds: [
                            'fcj9ynw7bv5umbn6zz4i0oaju',
                            'wcovj0knz9cte7zihrsyi8180',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'm0mwi0z7hvw7ojp2z1aq34531',
                name: 'variables',
                schema: 'public',
                x: 900,
                y: 100,
                fields: [
                    {
                        id: 'awms5psl0hhtzk15q46y2ooax',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 't9hc2ia5p9k4ksaofuneubhov',
                        name: 'prompt_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mola0yststs7iry7i0y7mmaao',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 't6h5uk95705wuoqknr9s940zb',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '5la3p1g1pui2kczoc577hgwua',
                        name: 'var_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'string'",
                        createdAt: now,
                    },
                    {
                        id: 'no5nz8auu17x861a0yu90kokr',
                        name: 'default_value',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'fpjphh3ef40myejvwtdkxi16e',
                        name: 'required',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'eb4a4znphm7iw0x2t6mivdtzl',
                        name: 'validation_regex',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '500',
                        createdAt: now,
                    },
                    {
                        id: 'mkmqvtgjbi2viw6292ymti7tv',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'jzsgviayn5e1ia1nswcpnbsaa',
                        name: 'variables_pkey',
                        unique: true,
                        fieldIds: ['awms5psl0hhtzk15q46y2ooax'],
                        createdAt: now,
                    },
                    {
                        id: 'z0ef4p9absaz3guhzkys6x4xg',
                        name: 'variables_prompt_id_name_unique',
                        unique: true,
                        fieldIds: [
                            't9hc2ia5p9k4ksaofuneubhov',
                            'mola0yststs7iry7i0y7mmaao',
                        ],
                        createdAt: now,
                    },
                    {
                        id: '9e8639gywbt4uq2og8eufxmfr',
                        name: 'idx_variables_prompt',
                        unique: false,
                        fieldIds: ['t9hc2ia5p9k4ksaofuneubhov'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xii7uwcytr5cs94eqqjlpda6a',
                name: 'tags',
                schema: 'public',
                x: 1300,
                y: 100,
                fields: [
                    {
                        id: 'iqw0farim8lduqhcmji37aiic',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'zzjhrf6yush1m9mf3jos69c5w',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: true,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'wl2grzah6nh43u1tp8ybo95co',
                        name: 'color',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '7',
                        createdAt: now,
                    },
                    {
                        id: 'ed2i6rwisqgmvpfzgt5nzq86a',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'k9lz077vp3cejph5knyhqrkwc',
                        name: 'tags_pkey',
                        unique: true,
                        fieldIds: ['iqw0farim8lduqhcmji37aiic'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '8ae4bfstrlqvyjt2w1ba4ezqn',
                name: 'prompt_tags',
                schema: 'public',
                x: 100,
                y: 600,
                fields: [
                    {
                        id: 'hgw0ddnl51zpzdsimoz27p711',
                        name: 'prompt_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '4w6ei1phty0np33pg4hi3yfrf',
                        name: 'tag_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'xryvirkb24fkcg30tu0q6rb3i',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '98t3aqwd1e99lzfdh3waoagnl',
                        name: 'prompt_tags_pkey',
                        unique: true,
                        fieldIds: [
                            'hgw0ddnl51zpzdsimoz27p711',
                            '4w6ei1phty0np33pg4hi3yfrf',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '0qtw428x2714jh2h86lzqihkw',
                name: 'test_cases',
                schema: 'public',
                x: 500,
                y: 600,
                fields: [
                    {
                        id: 'grydne0orl9fu7e3gi2rjfun1',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '3u83zj67u692lfpqc593fxyx4',
                        name: 'prompt_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mt7f7e40v44j2x6n7onr5nk05',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'lyg1ty5tx4pzaf1sa1y6bperv',
                        name: 'input_variables',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '171f9jamqt5jwjigx8ccztosd',
                        name: 'expected_output',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ly4obsa7m6zr0l28q2z786ei7',
                        name: 'expected_contains',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nmbl5hllt4foocfv8086ag5dj',
                        name: 'expected_not_contains',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'yfp9ktzudulsfmxw64hoo5f30',
                        name: 'max_latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '32s3a29zmls3uazamx12kwl7d',
                        name: 'created_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'w96pjrhuiq4vtn5qzqi6w90cl',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'fg33ypv8zos39ug7aa98sg0hf',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'w71ggaazcjf2nwpxwul9j8dr6',
                        name: 'test_cases_pkey',
                        unique: true,
                        fieldIds: ['grydne0orl9fu7e3gi2rjfun1'],
                        createdAt: now,
                    },
                    {
                        id: '1vh5mah4p1o1kka4jjzzb5itb',
                        name: 'idx_test_cases_prompt',
                        unique: false,
                        fieldIds: ['3u83zj67u692lfpqc593fxyx4'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c8vzpx07pr5zrjecnbtxemwnw',
                name: 'evaluations',
                schema: 'public',
                x: 900,
                y: 600,
                fields: [
                    {
                        id: 'ru8tybu6g11meybnlyowdnj8v',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'ngc3vll40gfh7ssh74x9voz6e',
                        name: 'prompt_version_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'o2g176jd5fmrao1q3gm6rhh6e',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'memfbzziuzstp7gztc7boz5lh',
                        name: 'model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'p28rwl2f1uwzymuz4b8m787cs',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'pending'",
                        createdAt: now,
                    },
                    {
                        id: 'ytbyjj1vjkb3p13qgj5nu506q',
                        name: 'total_cases',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '4fxxkzryzfl6dgulrpb0vjcad',
                        name: 'passed_cases',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'etladws3u45kx0v4gnfiioosa',
                        name: 'failed_cases',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'r2ni4rmt8jfvmskxvihc6p9gt',
                        name: 'avg_latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ugp9btnt2z6fooprl9cafv37c',
                        name: 'avg_cost_cents',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        createdAt: now,
                    },
                    {
                        id: 'asgc3w3m9x1i1wbteebkbhabi',
                        name: 'started_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kaqul7j24gidfsh6qumoivbpb',
                        name: 'completed_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '0nbiqsm4c51ai8l8l4yr2loty',
                        name: 'created_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'cd6fajvprxuyc2s8q47s3co14',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'gap547kj3hpagfntis5nksber',
                        name: 'evaluations_pkey',
                        unique: true,
                        fieldIds: ['ru8tybu6g11meybnlyowdnj8v'],
                        createdAt: now,
                    },
                    {
                        id: 'p42hep4ka51cewc9pe6hofnmk',
                        name: 'idx_evaluations_version',
                        unique: false,
                        fieldIds: ['ngc3vll40gfh7ssh74x9voz6e'],
                        createdAt: now,
                    },
                    {
                        id: '4wnkt1nfjolu39qm6s3mmfq34',
                        name: 'idx_evaluations_status',
                        unique: false,
                        fieldIds: ['p28rwl2f1uwzymuz4b8m787cs'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'rshfy2kp7akvvxl6mm0z7n8lg',
                name: 'eval_results',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: 'l4on97je0qa9nyucxuoj1sour',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'nz1ncdiy3erfnomkel3wedgty',
                        name: 'evaluation_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'r7ercxuna7lpw8gscviapscna',
                        name: 'test_case_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'a9rcfjkewo8n6jxn75ceu5hkd',
                        name: 'actual_output',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'mjdqqg44ajf1rzsv1n6pv64bs',
                        name: 'passed',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 's5q9yalygj4ocrmvgy6wvbfnw',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '9fddxjjbky5uminqcnpylti4y',
                        name: 'input_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'ycypq9h7nr93fqxrsrhk8o5j4',
                        name: 'output_tokens',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'kq6a16u8pxs0g2dpg29g6ssxt',
                        name: 'cost_cents',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 10,
                        scale: 4,
                        createdAt: now,
                    },
                    {
                        id: 'dn8d20cmogdg4lnnkjl229e7g',
                        name: 'failure_reason',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '7cg53v90k4sbdc6ytwmv2du79',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'zwl6q5jrhedfjxibnflwbga9e',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'sfmg1n5aapfh59fy5gfp0mlfu',
                        name: 'eval_results_pkey',
                        unique: true,
                        fieldIds: ['l4on97je0qa9nyucxuoj1sour'],
                        createdAt: now,
                    },
                    {
                        id: 'm8t6681cfhjy84wb9lrm43g0q',
                        name: 'idx_eval_results_evaluation',
                        unique: false,
                        fieldIds: ['nz1ncdiy3erfnomkel3wedgty'],
                        createdAt: now,
                    },
                    {
                        id: '240eyo2fx76lov1h0ljb6ou3x',
                        name: 'idx_eval_results_test_case',
                        unique: false,
                        fieldIds: ['r7ercxuna7lpw8gscviapscna'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '7nezkdk0hen7vdnzu9rc1zhrj',
                name: 'deployments',
                schema: 'public',
                x: 100,
                y: 1100,
                fields: [
                    {
                        id: 'g0n50oardyea55ys97muot8an',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'cny9zbonr863d472hyp8i3yyg',
                        name: 'prompt_version_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'it3998h3kw29mklpriir91jbz',
                        name: 'environment',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'mh39pfq77lqykc6wqeek2ff3n',
                        name: 'is_active',
                        type: {
                            id: 'boolean',
                            name: 'boolean',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'true',
                        createdAt: now,
                    },
                    {
                        id: 'mgwj4l5lupae4t7wtjiov3ved',
                        name: 'deployed_by',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'pjh24jofaf4iie0lvaj6vugbf',
                        name: 'rollback_version_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'rbm8yajj7s82m2vod7om39qwx',
                        name: 'deployed_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'uvds9y537cnkzw4y7kyxnbnll',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '0bpu20zjasm8qw7882tyfw6ln',
                        name: 'deployments_pkey',
                        unique: true,
                        fieldIds: ['g0n50oardyea55ys97muot8an'],
                        createdAt: now,
                    },
                    {
                        id: '6b18eja79kbmcxa3mhrgbkk1d',
                        name: 'idx_deployments_version',
                        unique: false,
                        fieldIds: ['cny9zbonr863d472hyp8i3yyg'],
                        createdAt: now,
                    },
                    {
                        id: 'lqc4z142epvnk050sz6sad12o',
                        name: 'idx_deployments_env',
                        unique: false,
                        fieldIds: [
                            'it3998h3kw29mklpriir91jbz',
                            'mh39pfq77lqykc6wqeek2ff3n',
                        ],
                        createdAt: now,
                    },
                ],
                color: '#ffcc5c',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: '82a0c4out45ul4yabfhqmhrn1',
                name: 'prompt_versions_prompt_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8wvmk64tgrtot2hfvduvesrlm',
                targetTableId: 'b73lg4u2kasji7cy98jwy8a6b',
                sourceFieldId: 'fcj9ynw7bv5umbn6zz4i0oaju',
                targetFieldId: '01cjrhomo149b9njbxj4yf9ec',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'n4u395a98zf0gh72i6jeaibt7',
                name: 'variables_prompt_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'm0mwi0z7hvw7ojp2z1aq34531',
                targetTableId: 'b73lg4u2kasji7cy98jwy8a6b',
                sourceFieldId: 't9hc2ia5p9k4ksaofuneubhov',
                targetFieldId: '01cjrhomo149b9njbxj4yf9ec',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '4jkqye8nf0znpj09rojajlh7e',
                name: 'prompt_tags_prompt_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8ae4bfstrlqvyjt2w1ba4ezqn',
                targetTableId: 'b73lg4u2kasji7cy98jwy8a6b',
                sourceFieldId: 'hgw0ddnl51zpzdsimoz27p711',
                targetFieldId: '01cjrhomo149b9njbxj4yf9ec',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '1utxk50x6wth3uy63qdry7ol0',
                name: 'prompt_tags_tag_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '8ae4bfstrlqvyjt2w1ba4ezqn',
                targetTableId: 'xii7uwcytr5cs94eqqjlpda6a',
                sourceFieldId: '4w6ei1phty0np33pg4hi3yfrf',
                targetFieldId: 'iqw0farim8lduqhcmji37aiic',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '8ywlw85qxyhbg62rbtnajfd8n',
                name: 'test_cases_prompt_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '0qtw428x2714jh2h86lzqihkw',
                targetTableId: 'b73lg4u2kasji7cy98jwy8a6b',
                sourceFieldId: '3u83zj67u692lfpqc593fxyx4',
                targetFieldId: '01cjrhomo149b9njbxj4yf9ec',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'iyw9nfcin7tsl9bfd5pf72w88',
                name: 'evaluations_prompt_version_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c8vzpx07pr5zrjecnbtxemwnw',
                targetTableId: '8wvmk64tgrtot2hfvduvesrlm',
                sourceFieldId: 'ngc3vll40gfh7ssh74x9voz6e',
                targetFieldId: 'scfr2vrulc7esjm0rwurz1xpb',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '9il29waz4pxt58pmocnzttg1w',
                name: 'eval_results_evaluation_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rshfy2kp7akvvxl6mm0z7n8lg',
                targetTableId: 'c8vzpx07pr5zrjecnbtxemwnw',
                sourceFieldId: 'nz1ncdiy3erfnomkel3wedgty',
                targetFieldId: 'ru8tybu6g11meybnlyowdnj8v',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '7fbyu87mdq3pp55ku7fov8j5h',
                name: 'eval_results_test_case_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'rshfy2kp7akvvxl6mm0z7n8lg',
                targetTableId: '0qtw428x2714jh2h86lzqihkw',
                sourceFieldId: 'r7ercxuna7lpw8gscviapscna',
                targetFieldId: 'grydne0orl9fu7e3gi2rjfun1',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'sq7kn0ba4gxvgddwdhzi8nerj',
                name: 'deployments_prompt_version_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '7nezkdk0hen7vdnzu9rc1zhrj',
                targetTableId: '8wvmk64tgrtot2hfvduvesrlm',
                sourceFieldId: 'cny9zbonr863d472hyp8i3yyg',
                targetFieldId: 'scfr2vrulc7esjm0rwurz1xpb',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'b9ji92ek7umgaz6hbzmsvvhh0',
                name: 'deployments_rollback_version_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '7nezkdk0hen7vdnzu9rc1zhrj',
                targetTableId: '8wvmk64tgrtot2hfvduvesrlm',
                sourceFieldId: 'pjh24jofaf4iie0lvaj6vugbf',
                targetFieldId: 'scfr2vrulc7esjm0rwurz1xpb',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
