import { DatabaseType } from '@/lib/domain/database-type';
import type { Template } from '../templates-data';
import image from '@/assets/templates/rag-pipeline.png';
import imageDark from '@/assets/templates/rag-pipeline-dark.png';

const now = Date.now();

export const ragPipelineDb: Template = {
    slug: 'rag-pipeline',
    name: 'RAG Pipeline',
    shortDescription: 'RAG pipeline with vectors, chunks, and retrieval',
    description:
        'Vector search, document processing, and retrieval-augmented generation pipeline',
    image,
    imageDark,
    tags: ['Postgres', 'AI', 'RAG'],
    featured: true,
    diagram: {
        id: 'rag_pipeline_db',
        name: 'rag-pipeline',
        createdAt: new Date(),
        updatedAt: new Date(),
        databaseType: DatabaseType.POSTGRESQL,
        tables: [
            {
                id: 'gw32cix9e0wjh5aegrddse0hy',
                name: 'collections',
                schema: 'public',
                x: 100,
                y: 100,
                fields: [
                    {
                        id: 'fpdm8to59ffuqavmrgymlf5om',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '17uwiymmw8fbb9zybr4jy9pqg',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'la013lswifvjxzdbxixg60ftr',
                        name: 'description',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'a7nqopgnt6tgt2ovvfou150yh',
                        name: 'embedding_model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        default: "'text-embedding-3-small'",
                        createdAt: now,
                    },
                    {
                        id: 'xdlvcmsv6lrpeck6vu4yd6u2a',
                        name: 'embedding_dimensions',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '1536',
                        createdAt: now,
                    },
                    {
                        id: 's8xywrx28av8h3eqcukhpd9bu',
                        name: 'chunk_strategy',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        default: "'recursive'",
                        createdAt: now,
                    },
                    {
                        id: 'jhw0cdolkoms9upo9lhxz97jm',
                        name: 'chunk_size',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '512',
                        createdAt: now,
                    },
                    {
                        id: 'l1jermd0mfppp4mfftyw9a57f',
                        name: 'chunk_overlap',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '50',
                        createdAt: now,
                    },
                    {
                        id: 'tt7ed6mb9i3dx1qnjmqzsywdt',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'd2pvn43ck0d0xy72n0vrtbqlt',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'cgau1mytsq4f0k05ht7o05kyi',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'warv9z7glmri5kujt4c4yr0so',
                        name: 'collections_pkey',
                        unique: true,
                        fieldIds: ['fpdm8to59ffuqavmrgymlf5om'],
                        createdAt: now,
                    },
                ],
                color: '#ff6b8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'y5hpjw7o7oaihpl7umggdf2u1',
                name: 'sources',
                schema: 'public',
                x: 500,
                y: 100,
                fields: [
                    {
                        id: 'wc5wsr6twvwdlbmtwojmhki8m',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'd20pwl1zsqb86uytz18al1ibr',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'sl102g0pfurlcli9l26p0w4wg',
                        name: 'name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: '1bw2l8t9boawhh8aftoa1ncki',
                        name: 'source_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: 'qpgbtlj3vrkvd3y8atblxofj1',
                        name: 'uri',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qv6qgu4ctb15vecdtmdlb945x',
                        name: 'mime_type',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'n2qzrtl0as0vqaw03rvdj9vzj',
                        name: 'file_size_bytes',
                        type: {
                            id: 'bigint',
                            name: 'bigint',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'wobtmscunvb8exf06bcwidie5',
                        name: 'checksum',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: 'pvn0nmenjcufpdm1lqj0fb7kc',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'gspqi6skhckti9gwlrh1sgtyb',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'pending'",
                        createdAt: now,
                    },
                    {
                        id: 'j73aya7i872p20bb6oq9anw5p',
                        name: 'error_message',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'nudyk2pcqz634xvaae078eou3',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                    {
                        id: 'fky5z1yf3u1rv1r9sqrttxtlg',
                        name: 'updated_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'xh0jvk4d37t0q029efgzsh0th',
                        name: 'sources_pkey',
                        unique: true,
                        fieldIds: ['wc5wsr6twvwdlbmtwojmhki8m'],
                        createdAt: now,
                    },
                    {
                        id: 'ohvsm8gsc5wnyu4w87tww5pme',
                        name: 'idx_sources_collection',
                        unique: false,
                        fieldIds: ['d20pwl1zsqb86uytz18al1ibr'],
                        createdAt: now,
                    },
                    {
                        id: '7l4ipfk83o7m8wtw5slwzwvzd',
                        name: 'idx_sources_status',
                        unique: false,
                        fieldIds: ['gspqi6skhckti9gwlrh1sgtyb'],
                        createdAt: now,
                    },
                ],
                color: '#8eb7ff',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'xcom9da34ar9w391jatsm7byf',
                name: 'documents',
                schema: 'public',
                x: 900,
                y: 100,
                fields: [
                    {
                        id: 'iths41jv8mmprwymvd5m06dpk',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '3ch0n10rtt0fwglj30cwbo6bz',
                        name: 'source_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'aalrkducgn1qq25zzylhxj6hg',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'tdmoqzpjp2c7m13lupuj3x5pp',
                        name: 'title',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '500',
                        createdAt: now,
                    },
                    {
                        id: 'cfwx1z52i75nddits16m5sxdv',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vuum4kkf6vw496nir3ngks39h',
                        name: 'content_hash',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '64',
                        createdAt: now,
                    },
                    {
                        id: 'myzgt9fgpzroxy7ernp6t2u79',
                        name: 'page_number',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 's7sco266bnftx2me6beljcokv',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'pbbeiw6umoa3zfju7usxmtukw',
                        name: 'token_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'cy0dfzgtfgm9b6rrnqasycl78',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '2hse2zdlnla6pb8nbszz7ikk7',
                        name: 'documents_pkey',
                        unique: true,
                        fieldIds: ['iths41jv8mmprwymvd5m06dpk'],
                        createdAt: now,
                    },
                    {
                        id: 'h8f4scv8yr3jrvpmzcw8h8ecm',
                        name: 'idx_documents_source',
                        unique: false,
                        fieldIds: ['3ch0n10rtt0fwglj30cwbo6bz'],
                        createdAt: now,
                    },
                    {
                        id: '1ianfql7zmq68dewfpmvihx09',
                        name: 'idx_documents_collection',
                        unique: false,
                        fieldIds: ['aalrkducgn1qq25zzylhxj6hg'],
                        createdAt: now,
                    },
                ],
                color: '#4dee8a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '76jtmkcvwtsgoba2s4q0v5apw',
                name: 'chunks',
                schema: 'public',
                x: 1300,
                y: 100,
                fields: [
                    {
                        id: '1oevcz1zevdp7rzrbxrd9znql',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'f3g07buemzy5o98bsjq5rv10b',
                        name: 'document_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'bqbarc2x2qa7z3rig1wkh64t5',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '2uxf9hra6o28hx584jlywbfvn',
                        name: 'content',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '7smq8l2xb39nqorpi3hvvnfno',
                        name: 'chunk_index',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'ndwb3iel89m4d8r6k1tcnyw8g',
                        name: 'token_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'kgo3vtjkdx0jpg02gqbdcl4be',
                        name: 'start_offset',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'mi4brggr8hkctfd6wamx6ymoa',
                        name: 'end_offset',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'qusugfgo7gad8uuepdh7khpq6',
                        name: 'metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'hm5o8ohwnaqxgbp30rm03yij2',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '5l7l629nw1v5tmyifcm2flxn3',
                        name: 'chunks_pkey',
                        unique: true,
                        fieldIds: ['1oevcz1zevdp7rzrbxrd9znql'],
                        createdAt: now,
                    },
                    {
                        id: 'bocvwtc6s1fgm588njcp2c63w',
                        name: 'idx_chunks_document',
                        unique: false,
                        fieldIds: ['f3g07buemzy5o98bsjq5rv10b'],
                        createdAt: now,
                    },
                    {
                        id: 'u40zb6gha7uowxwkkd7net1zv',
                        name: 'idx_chunks_collection',
                        unique: false,
                        fieldIds: ['bqbarc2x2qa7z3rig1wkh64t5'],
                        createdAt: now,
                    },
                ],
                color: '#ff9f74',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'sm67gj7eetmaas428tg2sooo3',
                name: 'embeddings',
                schema: 'public',
                x: 100,
                y: 600,
                fields: [
                    {
                        id: 'jc7pfclqeolcwrq1boy9opqxd',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'ffexm0tm9m12eso4wh6ycne5f',
                        name: 'chunk_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'b2uidx2buebviajqkx1zh1u9o',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'imiwey66lov6a8rh9ucszndbx',
                        name: 'model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: '41pboetunukbt1e384c67z257',
                        name: 'dimensions',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'vh9i0sdk8m3e7iuzx1r6lxxfz',
                        name: 'vector_data',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'jypxiwurgzovqlwpr8l1fz3yp',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'jly2yta9dzil04ec9y15lnphs',
                        name: 'embeddings_pkey',
                        unique: true,
                        fieldIds: ['jc7pfclqeolcwrq1boy9opqxd'],
                        createdAt: now,
                    },
                    {
                        id: 'q6m1929eg7iwxgg2oh40yrkmr',
                        name: 'idx_embeddings_chunk',
                        unique: false,
                        fieldIds: ['ffexm0tm9m12eso4wh6ycne5f'],
                        createdAt: now,
                    },
                    {
                        id: 'h7sfn7c4hefx4xi2oi9997w4n',
                        name: 'idx_embeddings_collection',
                        unique: false,
                        fieldIds: ['b2uidx2buebviajqkx1zh1u9o'],
                        createdAt: now,
                    },
                ],
                color: '#b067e9',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'ditg51ac5i803ysrt83yre4s2',
                name: 'vector_stores',
                schema: 'public',
                x: 500,
                y: 600,
                fields: [
                    {
                        id: 'gtsxaqzf9vqftzbut0w5hnckb',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'jme9m9jmy1mh0k1d7f0yjjbig',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'hf8thu78vqktsxb6709j8gyr8',
                        name: 'provider',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '50',
                        createdAt: now,
                    },
                    {
                        id: '5tuq845p81zy16yc4exonnrw0',
                        name: 'index_name',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'm0maoll0dgdz7gmhy00ipom16',
                        name: 'config',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        default: "'{}'",
                        createdAt: now,
                    },
                    {
                        id: 'cvi4cq6ryjq0karbytl89rgd8',
                        name: 'document_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: 'thrsunql3fkquuzcri49hxg5l',
                        name: 'chunk_count',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '0',
                        createdAt: now,
                    },
                    {
                        id: '0a3ij9u9ao1xz9wd2cza79o8d',
                        name: 'status',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        characterMaximumLength: '20',
                        default: "'active'",
                        createdAt: now,
                    },
                    {
                        id: 'a7tc6sin77jyiv0aaz9xandzn',
                        name: 'last_synced_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'gp0t81wd122cx1p1gkvc257w7',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'n5fhe12bcc4vb264swnnlaao1',
                        name: 'vector_stores_pkey',
                        unique: true,
                        fieldIds: ['gtsxaqzf9vqftzbut0w5hnckb'],
                        createdAt: now,
                    },
                ],
                color: '#7175fa',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: '6cl8i0inm0k0a07nl8xbdkwss',
                name: 'retrieval_queries',
                schema: 'public',
                x: 900,
                y: 600,
                fields: [
                    {
                        id: '88pw3u3f98eyvyw3o26ww2qnv',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'v8fdi74ovr3uw7zpp29elvf0o',
                        name: 'collection_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '80yjvhsemm1rjd0fto86os53m',
                        name: 'query_text',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '46u1vya2cn3nf0wtxjufuo8qd',
                        name: 'query_embedding',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '9ud1vutyta017uyadcf57tot8',
                        name: 'top_k',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: '5',
                        createdAt: now,
                    },
                    {
                        id: '00s6uga3ngj6243bzck21n3qb',
                        name: 'similarity_threshold',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 5,
                        scale: 4,
                        default: '0.7',
                        createdAt: now,
                    },
                    {
                        id: 'cimr33j68wigec3tw7pkqxwk5',
                        name: 'filter_metadata',
                        type: {
                            id: 'jsonb',
                            name: 'jsonb',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1h31ll0kq4wiymipskrd1rej8',
                        name: 'rerank_model',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '100',
                        createdAt: now,
                    },
                    {
                        id: 'm8d3fby89kwszv4p6lc245cxz',
                        name: 'latency_ms',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: '1j2ye8wpmqf31z4afoe6mhdhi',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 's9qff8proccxa8715xkgc2k2y',
                        name: 'retrieval_queries_pkey',
                        unique: true,
                        fieldIds: ['88pw3u3f98eyvyw3o26ww2qnv'],
                        createdAt: now,
                    },
                    {
                        id: 'hhkacqh7bbd78h6nd6g8zs4j2',
                        name: 'idx_retrieval_queries_collection',
                        unique: false,
                        fieldIds: ['v8fdi74ovr3uw7zpp29elvf0o'],
                        createdAt: now,
                    },
                ],
                color: '#c05dcf',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'a5mzbpukbm8ddfldcsz0vufsd',
                name: 'retrieval_results',
                schema: 'public',
                x: 1300,
                y: 600,
                fields: [
                    {
                        id: 'u40iu86rs61n2t65ivsmj4j62',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: 'xm80u5p9g98hdatr7aw8uvdue',
                        name: 'query_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'uwf4e9gm6rt84rpgd0x6dn5vr',
                        name: 'chunk_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: '5juixelodpim2ggziww37a95n',
                        name: 'similarity_score',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        precision: 7,
                        scale: 6,
                        createdAt: now,
                    },
                    {
                        id: '46qxiw2e6f1bmza2arr9lzvbi',
                        name: 'rerank_score',
                        type: {
                            id: 'numeric',
                            name: 'numeric',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        precision: 7,
                        scale: 6,
                        createdAt: now,
                    },
                    {
                        id: 's24ori42v3ka0h13ri3lyikqh',
                        name: 'rank_position',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yc9632ng0vdvfp1l8zp0o1zu6',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: 'bb2hvz3hl8f2j5nnp53ifx62t',
                        name: 'retrieval_results_pkey',
                        unique: true,
                        fieldIds: ['u40iu86rs61n2t65ivsmj4j62'],
                        createdAt: now,
                    },
                    {
                        id: 'fzzh7vxv892sc3objt1i829b4',
                        name: 'idx_retrieval_results_query',
                        unique: false,
                        fieldIds: ['xm80u5p9g98hdatr7aw8uvdue'],
                        createdAt: now,
                    },
                ],
                color: '#9ef07a',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
            {
                id: 'c7mrwopdufnrzrjj2di8j1umx',
                name: 'feedback',
                schema: 'public',
                x: 100,
                y: 1100,
                fields: [
                    {
                        id: 'mydw2uegtvbji0o8hox8cpc6u',
                        name: 'id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: true,
                        unique: true,
                        nullable: false,
                        default: 'gen_random_uuid()',
                        createdAt: now,
                    },
                    {
                        id: '0djk12tqq0bue6x9h2idobuvb',
                        name: 'query_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'yyoo0hgr3ps21qzyg7cy5rs7t',
                        name: 'result_id',
                        type: {
                            id: 'uuid',
                            name: 'uuid',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'v67r9y7dm6j388aw33tgc5yv5',
                        name: 'rating',
                        type: {
                            id: 'integer',
                            name: 'integer',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        createdAt: now,
                    },
                    {
                        id: 'f996s4p2mkg32zv0fi9mutbuo',
                        name: 'comment',
                        type: {
                            id: 'text',
                            name: 'text',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        createdAt: now,
                    },
                    {
                        id: 'dlglk98b3qu7izxo642cllon1',
                        name: 'user_id',
                        type: {
                            id: 'varchar',
                            name: 'varchar',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: true,
                        characterMaximumLength: '255',
                        createdAt: now,
                    },
                    {
                        id: 'foske18z5z8dk1eh5eptbze4d',
                        name: 'created_at',
                        type: {
                            id: 'timestamptz',
                            name: 'timestamptz',
                        },
                        primaryKey: false,
                        unique: false,
                        nullable: false,
                        default: 'now()',
                        createdAt: now,
                    },
                ],
                indexes: [
                    {
                        id: '8bvaz499p9krnha33f9u80i3k',
                        name: 'feedback_pkey',
                        unique: true,
                        fieldIds: ['mydw2uegtvbji0o8hox8cpc6u'],
                        createdAt: now,
                    },
                    {
                        id: 'c1g78njvqvmw1agjb850ccikt',
                        name: 'idx_feedback_query',
                        unique: false,
                        fieldIds: ['0djk12tqq0bue6x9h2idobuvb'],
                        createdAt: now,
                    },
                ],
                color: '#ffcc5c',
                isView: false,
                isMaterializedView: false,
                createdAt: now,
            },
        ],
        relationships: [
            {
                id: 'tfxe3x54i1oc15wpt8gw3cjst',
                name: 'sources_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'y5hpjw7o7oaihpl7umggdf2u1',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'd20pwl1zsqb86uytz18al1ibr',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'da1thyg57ytvgd3jq62nfw7l1',
                name: 'documents_source_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xcom9da34ar9w391jatsm7byf',
                targetTableId: 'y5hpjw7o7oaihpl7umggdf2u1',
                sourceFieldId: '3ch0n10rtt0fwglj30cwbo6bz',
                targetFieldId: 'wc5wsr6twvwdlbmtwojmhki8m',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '3vnommqeahjvgcoe39thgp9br',
                name: 'documents_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'xcom9da34ar9w391jatsm7byf',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'aalrkducgn1qq25zzylhxj6hg',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'pnetfs8gb3egec7wvyqbqct6s',
                name: 'chunks_document_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '76jtmkcvwtsgoba2s4q0v5apw',
                targetTableId: 'xcom9da34ar9w391jatsm7byf',
                sourceFieldId: 'f3g07buemzy5o98bsjq5rv10b',
                targetFieldId: 'iths41jv8mmprwymvd5m06dpk',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '5pqup9eyjyxird5lky4tyw6uh',
                name: 'chunks_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '76jtmkcvwtsgoba2s4q0v5apw',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'bqbarc2x2qa7z3rig1wkh64t5',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'f9ijrl4tkp6d3ail4y9atznk0',
                name: 'embeddings_chunk_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'sm67gj7eetmaas428tg2sooo3',
                targetTableId: '76jtmkcvwtsgoba2s4q0v5apw',
                sourceFieldId: 'ffexm0tm9m12eso4wh6ycne5f',
                targetFieldId: '1oevcz1zevdp7rzrbxrd9znql',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'ueo9nsgvgb2l3c1i3ddmpf3hi',
                name: 'embeddings_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'sm67gj7eetmaas428tg2sooo3',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'b2uidx2buebviajqkx1zh1u9o',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'fn6ncezycay3a6oeadpuht4d3',
                name: 'vector_stores_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'ditg51ac5i803ysrt83yre4s2',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'jme9m9jmy1mh0k1d7f0yjjbig',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'jedwr4cus0tboma800stg5qpc',
                name: 'retrieval_queries_collection_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: '6cl8i0inm0k0a07nl8xbdkwss',
                targetTableId: 'gw32cix9e0wjh5aegrddse0hy',
                sourceFieldId: 'v8fdi74ovr3uw7zpp29elvf0o',
                targetFieldId: 'fpdm8to59ffuqavmrgymlf5om',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'uk990jymr6igkzohk2jg3a8x2',
                name: 'retrieval_results_query_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'a5mzbpukbm8ddfldcsz0vufsd',
                targetTableId: '6cl8i0inm0k0a07nl8xbdkwss',
                sourceFieldId: 'xm80u5p9g98hdatr7aw8uvdue',
                targetFieldId: '88pw3u3f98eyvyw3o26ww2qnv',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '70d28ynierppka8v31wb9f6yk',
                name: 'retrieval_results_chunk_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'a5mzbpukbm8ddfldcsz0vufsd',
                targetTableId: '76jtmkcvwtsgoba2s4q0v5apw',
                sourceFieldId: 'uwf4e9gm6rt84rpgd0x6dn5vr',
                targetFieldId: '1oevcz1zevdp7rzrbxrd9znql',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: 'nfclzxd76oalq4uyk8foyi94s',
                name: 'feedback_query_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c7mrwopdufnrzrjj2di8j1umx',
                targetTableId: '6cl8i0inm0k0a07nl8xbdkwss',
                sourceFieldId: '0djk12tqq0bue6x9h2idobuvb',
                targetFieldId: '88pw3u3f98eyvyw3o26ww2qnv',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
            {
                id: '84xvgk8412ggnzyq9n4z0pewt',
                name: 'feedback_result_id_fkey',
                sourceSchema: 'public',
                targetSchema: 'public',
                sourceTableId: 'c7mrwopdufnrzrjj2di8j1umx',
                targetTableId: 'a5mzbpukbm8ddfldcsz0vufsd',
                sourceFieldId: 'yyoo0hgr3ps21qzyg7cy5rs7t',
                targetFieldId: 'u40iu86rs61n2t65ivsmj4j62',
                sourceCardinality: 'many',
                targetCardinality: 'one',
                createdAt: now,
            },
        ],
        dependencies: [],
    },
};
